#%%
import mne
import re
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import glob
import os
import meegkit
from mne.datasets import sample
# from mne.stats.regression import linear_regression_raw
from sklearn.linear_model import Ridge
from sklearn.preprocessing import StandardScaler
import scipy
from functools import partial
from mne_custom_regression import ridge_regression_raw, ridge_model, plot_with_stats, plot_cluster, comprehension_above_chance
import seaborn as sns
sns.set_palette("tab10")
import traceback
# get current dir to construct relative paths
dir_path = os.path.dirname(os.path.realpath(__file__))
os.chdir(dir_path)
pd.options.mode.chained_assignment = None  # default='warn'

#################
# this version: as for V8 but 
# - categorical dummy coded regressor for type of fixation (word, stop, punc)
# - separate MW effect estimated for each of the above
vnum = 9 
#################

#%% paths
dir_raw = '/Volumes/Blue1TB/EyeMindLink/Data'
dir_fif = '/Volumes/Blue1TB/EEG_processed/preprocessed_fif/'
event_fn_suffix = '_eyetracker_events.csv' # inside dir_fif, events containing fixations sacs and blinks as well as tasks, generated by merge_eyetracker_eeg.py
dir_out_par = '/Volumes/Blue1TB/EEG_processed/'
REDO = False
FORCE_REDO = False
channels = ['CPz', 'FCz', 'AFF5h', 'AFF6h', 'CCP5h', 'CCP6h', 'PPO9h', 'PPO10h']
decimation = 10 #TODO: set to 1 for final pass analysis
ridge_alpha=1
verstr = f'FRP_TRF_lexical_v{vnum}_alpha{ridge_alpha}_decim{decimation}'
dir_out = os.path.join(dir_out_par, verstr)



os.makedirs(dir_out, exist_ok=True)
dir_events = os.path.expanduser('~/Emotive Computing Dropbox/Rosy Southwell/EyeMindLink/Processed/events/') # task events
ia_df = pd.read_csv('../info/ia_label_mapping_opt_surprisal.csv').rename(columns={'gpt2_surprisal_page':'surprisal'})
ia_df['IA_ID'] = ia_df['IA_ID'].fillna('-1').astype(float).astype(int)
ia_df['log_word_freq'] = ia_df['word_freq'].astype(float).apply(np.log).replace(-np.inf, np.nan)

beh_df = pd.read_csv('~/Emotive Computing Dropbox/Rosy Southwell/EyeMindLink/Processed/Behaviour/EML1_page_level.csv') # comp and MW scores
eeg_trigger_df = pd.read_csv('../info/EEGtriggerSources.csv')
fn_base = '_p.fif'

pIDs = [re.findall(r'EML1_\d{3}', f)[0] for f in os.listdir(dir_fif) if f.endswith(fn_base)]
# unique and sort
pIDs = sorted(list(set(pIDs)))
exclude = [20, 21, 22, 23, 24, 25, 26, 27, 30, 31, 39, 40, 73, 77, 78, 87,88,93,99, 
    110,115,123,125, 138, 160, 164,167,168, 171,172,173, 178,179] # ubj to exclude because no eeg or no trigger etc.
skip_reasons = {} if REDO else pd.read_csv(os.path.join(dir_out, 'skip_reasons.csv'), index_col=0).to_dict()['0']
# fill NaN with '' in skip_reasons
for pID in pIDs:
    skip_reasons[pID] = skip_reasons.get(pID, '')
    if pd.isna(skip_reasons[pID]):
        skip_reasons[pID] = ''
    if int(re.findall(r'\d{3}', pID)[0]) in exclude:
        skip_reasons[pID] = 'no eeg or no IAs'
pIDs = [p for p in pIDs if int(re.findall(r'\d{3}', p)[0]) not in exclude]


# #####
# pIDs = ['EML1_166'] #TMP
# resume_from = 'EML1_070'
# pIDs = pIDs[pIDs.index(resume_from):]
# #####


#%% Loop over subjects

if REDO:
    cond_counts_all = []

    rERP_ALL = []
    for pID in pIDs: 
        # try:
            # check if this pID already has a result
            if os.path.exists(os.path.join(dir_out, f'{pID}_rERP-evk.fif')) and not FORCE_REDO:
                    print(f'{pID} already processed, skipping')
                    continue
            print('\n')
            print(f'Processing {pID}')
            mne.set_log_level('ERROR')
            ##### load 
            EEG = mne.io.read_raw_fif(os.path.join(dir_fif, f'{pID}_p.fif'), preload=True)
            # check all channels are present
            if set(channels).isdisjoint(EEG.ch_names):
                print(f'{pID} does not contain all channels, skipping')
                skip_reasons[pID] = 'missing channels'
                raise Exception(f'{pID} does not contain all channels, skipping')
            # check for bad channels and interpolate them
            if EEG.info['bads']:
                print(f'Interpolating bad channels {EEG.info["bads"]}')
                EEG.interpolate_bads()

            ## task events
            with open(os.path.join(dir_fif, f'{pID}-info.txt')) as f:
                triginfo = f.read()
            task_events = pd.read_csv(os.path.join(dir_events, f'{pID}_events.csv')).rename(columns={'EVENT':'identifier','TrialType':'task'})
            # copy the correct EEGsample column for use depending on triginfo
            if 'LA0' in triginfo:
                task_events['eeg_sample'] = task_events['eegSD_sample_est'].astype(float).astype(int)
            else:
                task_events['eeg_sample'] = task_events['eeg_sample_est'].astype(float).astype(int)
            task_events['event_type'] = 'ButtonPress'
            # we want to model buttonpresses at the end of reading too, which are sometimes questions i.e. 'MW','SVT','Deep','Inference','Rote'
            task_events['task']=task_events['task'].fillna('other')
            task_events.loc[task_events['task'].str.contains('MW|SVT|Deep|Inference|Rote'), 'task'] = 'reading'
            task_events['latency_sec'] = task_events['eeg_sample']/EEG.info['sfreq']

            ## eye events
            events = pd.read_csv(os.path.join(dir_fif, f'{pID}{event_fn_suffix}'))
            cols = ['event_type', 'task', 'identifier', 'description', 'eye', 'eeg_sample',
                'latency_sec', 'duration_sec', 
                'fix_pupilAvg', 'fix_pageIndex', 'IA_ID', 'IA_LABEL', 'INBOUND_SAC_AMPLITUDE']
            task_events = task_events[[c for c in cols if c in task_events.columns]]
            events = pd.concat([events[cols], task_events])
            # treat '.' as missing in 'IA_ID'
            events['IA_ID'] = events['IA_ID'].replace('.', np.nan).fillna('-1').astype(int)
            if events['IA_ID'].nunique()==1 and events['IA_ID'].unique()[0]==-1:
                print(f'{pID} has no IA_IDs, skipping')
                skip_reasons[pID] = 'no IA_IDs'
                continue
            events['eeg_sample'] = events['eeg_sample'].astype(float).astype(int)
            # check if all events are from same eye, if not, keep only Right
            if not events['eye'].nunique()==1:
                print(f'{pID} has events from both eyes, keeping only right')
                events = events[events['eye']=='R']
            # rename all fixations as Fixation regardless of eye
            events['event_type'] = events['event_type'].replace('Fixation_R-reparsed','Fixation')
            events['event_type'] = events['event_type'].replace('Fixation_L-reparsed','Fixation')
            events['event_type'] = events['event_type'].replace('Fixation_R','Fixation')
            events['event_type'] = events['event_type'].replace('Fixation_L','Fixation')

            events['identifier'] = events['identifier'].fillna('') # some are NaN
            events['task'] = events['task'].fillna('none') # some are NaN
            events['event_type'] = events['event_type'].fillna('other') # some are NaN
            events = events.drop_duplicates(subset=['latency_sec','description'])
            beh_df_i = beh_df[beh_df['ParticipantID']==pID]
            beh_df_i['identifier'] = beh_df_i['Text'].astype(str) + (beh_df_i['PageNum']-1).astype(str)
            # merge lexical properties to events by IA_ID, which needs to be forced to be a string formatted as an integer not a float like 1.0
            events = events.merge(ia_df, how='left')
            events = events.merge(beh_df_i, how='left')
            events['task+type'] = events['task'] + '/' + events['event_type']
            # make annotations from events
            annot_all = mne.Annotations(onset=events['latency_sec'], duration=events['duration_sec'], description=events['task+type'])
            EEG.set_annotations(annot_all)


            ##### apply preprocessing to EEG (interp bads and reref alraedy done)
            EEG.filter(0.5, 15)

            ##### select events
            # select only reading and sham for 'task'
            events = events[events['task'].str.contains('reading|sham')]
            fixations = events[events['event_type'].str.contains('Fixation') ]
            blinks = events[events['event_type'].str.contains('Blink')]
            task_events = events[events['event_type'].str.contains('ButtonPress')]       

            # get sacc amp outliers for this participant as +- 3 STDEV from the mean INBOUND_SAC_AMPLITUDE
            sacc_amp_outliers = np.abs(fixations['INBOUND_SAC_AMPLITUDE'] - fixations['INBOUND_SAC_AMPLITUDE'].mean()) > 3*fixations['INBOUND_SAC_AMPLITUDE'].std()
            # drop fixations with extreme duration or saccade amplitude
            fixations = fixations[~sacc_amp_outliers]
            # remove fixations with duration <50 or >1000
            fixations = fixations[(fixations['duration_sec'] > 0.05) & (fixations['duration_sec'] < 1)]
            fixations = fixations.set_index('eeg_sample')
            
            # ##### word fixaitons as a separate event
            # fixations['event_type'].loc[fixations['IA_ID']!=-1 & (fixations['task']=='reading')] = 'FixationWord' 
            # fixations['event_type'].loc[fixations['IA_ID']!=-1 & (fixations['task']=='reading') & (fixations['stop_word']==1)] = 'STOP' # for stop words
            # fixations['event_type'].loc[fixations['IA_ID']!=-1 & (fixations['task']=='reading') & (fixations['punctuation']==1)] = 'PUNC' # for punctuation

            # ##### type of fixation as biary dummy coded variable (intercept = all fixations)
            fixations['WORD'] = np.where((fixations['IA_ID']!=-1) & (fixations['task']=='reading') & (fixations['stop_word']==0), 1, 0) # for words
            fixations['STOP'] = np.where((fixations['task']=='reading') & (fixations['stop_word']==1), 1, 0) # for stop words
            fixations['PUNC'] = np.where((fixations['task']=='reading') & (fixations['punctuation']==1), 1, 0) # for punctuation

            ##### MW 
            fixations['MW'] = fixations['MW'].fillna(-1).astype(int) # third condition coded as -1 for unknown
            # expand to dummy coded cols, one for MW=0 one for MW=1 (intercept is MW=-1)
            fixations['MW=0'] = (fixations['MW']==0).astype(int)
            fixations['MW=1'] = (fixations['MW']==1).astype(int)
            # interaction terms
            fixations['WORD_MW=0'] = fixations['MW=0'] * fixations['WORD'] # MW=0 and WORD
            fixations['WORD_MW=1'] = fixations['MW=1'] * fixations['WORD'] # MW=1 and WORD
            fixations['STOP_MW=0'] = fixations['MW=0'] * fixations['STOP'] # MW=0 and STOP
            fixations['STOP_MW=1'] = fixations['MW=1'] * fixations['STOP'] # MW=1 and STOP
            fixations['PUNC_MW=0'] = fixations['MW=0'] * fixations['PUNC'] # MW=0 and PUNC
            fixations['PUNC_MW=1'] = fixations['MW=1'] * fixations['PUNC'] # MW=1 and PUNC

            ##### covariates
            #  use latencies in trl to look up covariates in events
            lexical_covariates = ['surprisal', 'log_word_freq', 'relative_word_position']
            gaze_covariates = []
            cognitive_covariates = ['MW=0','MW=1',
                                    "WORD","STOP","PUNC", # these are the binary dummies for fixation types
                                    'WORD_MW=0', 'WORD_MW=1', # these are the interactions for word fixations
                                    'STOP_MW=0', 'STOP_MW=1', # these are the interactions for stop words 
                                    'PUNC_MW=0', 'PUNC_MW=1' # these are the interactions for punctuation
            ]

            ##### covariates
            # 
            # set lexical covariates to NA for all fixations except "WORD" 
            # this will ensure that only word fixations have lexical covariates
            fixations['surprisal'] = fixations['surprisal'].where(fixations['WORD'] == 1, np.nan) # only for word fixations
            fixations['log_word_freq'] = fixations['log_word_freq'].where(fixations['WORD'] == 1, np.nan) # only for word fixations
            # covariate interactions: separate lexical covariates for MW and no MW WORD fixations so we can look at interaction
            lexical_covariates_2 =[]
            for l in lexical_covariates:
                for c in cognitive_covariates:
                    if "WORD" not in c: # only want to do this for WORD fixations with interaction (as surprosal is only defined for word anyway)   
                        continue
                    fixations[f'{l}_{c}'] = np.where(fixations[c] == 1, fixations[l], np.nan)
                    lexical_covariates_2.append(f'{l}_{c}')
            lexical_covariates =  lexical_covariates_2 # in this case the new ones are perfectly collinear with main effect of the original lexical vars so we drop them to prevent signular covariate matrix
    
            ##### add blinks , buttonpress
            blinks['task+type'] = 'Blink'
            blinks.set_index('eeg_sample', inplace=True)
            task_events.set_index('eeg_sample', inplace=True)

            # concatenate covariate coplumns to fixations
            events_to_model = pd.concat([fixations, blinks, task_events])
            events_to_model = events_to_model.sort_values('eeg_sample').reset_index()
            # drop  duplicates on eeg sample taking into account decimation - GLM complains otherwise
            events_to_model['eeg_sample_decim'] = (events_to_model['eeg_sample']/decimation).astype(int)
            print(f'length before drop duplicates: {len(events_to_model)}')
            events_to_model = events_to_model.drop_duplicates(subset=['eeg_sample_decim'], keep='first')
            print(f'length after drop duplicates: {len(events_to_model)}')            
            # get covariates back oput of events now dupes have been droped
            covariates = events_to_model.loc[:,['eeg_sample']+lexical_covariates+gaze_covariates+cognitive_covariates]
            # scale and center copntinuous covariates (lex, gaze) but leave MW/refixations as is
            covariates.loc[:,lexical_covariates+gaze_covariates] = covariates.loc[:,lexical_covariates+gaze_covariates].apply(lambda x: (x-x.mean())/x.std(), axis=0)
            covariates = covariates.fillna(0) # so equiv to mean over non nulls

            # trick to get trl and trldict 
            annot_to_model = mne.Annotations(onset=events_to_model['latency_sec'], 
                                             duration=events_to_model['duration_sec'], 
                                             description=events_to_model['task+type'])            
            EEG.set_annotations(annot_to_model)
            trl_to_model, trldict_to_model = mne.events_from_annotations(EEG, regexp='.*Fixation*|.*Blink|.*ButtonPress')
            # check covariates same length as trl 
            if len(covariates) != len(trl_to_model):
                print(f'{pID} covariates and trl are different lengths')
                # get matching eeg_samples from trl first column and coviarates eeg_sample
                trl_eeg_samples = trl_to_model[:,0]
                cov_eeg_samples = covariates['eeg_sample']
                common = np.intersect1d(trl_eeg_samples, cov_eeg_samples)
                covariates = covariates[covariates['eeg_sample'].isin(common)]
                trl_to_model = trl_to_model[np.isin(trl_to_model[:,0], common)]
            # check if covariates is singular
            if np.linalg.matrix_rank(covariates) < covariates.shape[1]:
                print(f'{pID} covariates are singular')
                skip_reasons[pID] = 'singular covariates'
                # continue
            
            ##### count fixations per categorical condition
            cond_counts = {}
            for cond in ['WORD_MW=0', 'WORD_MW=1']:
                cond_counts[cond] = (events_to_model[cond]).sum()
                if cond_counts[cond] < 60:
                    print(f'{pID} has fewer than 60 fixations in condition {cond}')
                    skip_reasons[pID] = 'fewer than 60 fixations per condition'
            cond_counts['Fixation'] = (events_to_model['task+type']==('Fixation')).sum()
            cond_counts['pID'] = pID
            cond_counts_all.append(cond_counts)

            ##### model
            tmin, tmax = -0.3, 0.8
            loglevelwas = mne.set_log_level('WARNING', return_old_level=True)
            try:
                X, rERP, stats = ridge_regression_raw(
                    EEG, 
                    events=trl_to_model, event_id=trldict_to_model,
                    tmin=tmin, tmax=tmax, 
                    reject={'eeg': 120e-6}, # uV, as in DImigen Ehinger 2019
                    tstep=1,
                    decim=decimation, #TODO: replace w 1 when finalized
                    covariates=covariates.drop(columns=['eeg_sample']), 
                    model = partial(ridge_model, alpha=ridge_alpha),
                    estimate_pvals=False
                )
            except Exception as e:
                print(f'Error in fitting model for {pID}: {e}')
                skip_reasons[pID] = 'model fitting error: ' + str(e)
                continue
            ##### save stats
            save_fn = os.path.join(dir_out, f'{pID}_rERP_stats.npz')
            np.savez(save_fn, **stats)

            ##### plot overall fixation 
            fig=rERP['reading/Fixation'].plot()
            fig.savefig(os.path.join(dir_out, f'{pID}_FRP_butterfly.png'))
            
            ##### make rERPs from condition combinations
            rERP['FRP'] = rERP['reading/Fixation'] # this is the main fixation response potential
            rERP['FRP_WORD'] = mne.combine_evoked([rERP['WORD'], rERP['reading/Fixation']], weights=[1, 1])
            rERP['FRP_STOP'] = mne.combine_evoked([rERP['STOP'], rERP['reading/Fixation']], weights=[1, 1])
            rERP['FRP_PUNC'] = mne.combine_evoked([rERP['PUNC'], rERP['reading/Fixation']], weights=[1, 1]) 
            rERP['FRP_MW=0'] = mne.combine_evoked([rERP['MW=0'], rERP['reading/Fixation']], weights=[1, 1])
            rERP['FRP_MW=1'] = mne.combine_evoked([rERP['MW=1'], rERP['reading/Fixation']], weights=[1, 1])
            rERP['FRP_WORD_MW=0'] = mne.combine_evoked([rERP['FRP_WORD'], rERP['MW=0'], rERP['WORD_MW=0']], weights=[1, 1,1])
            rERP['FRP_WORD_MW=1'] = mne.combine_evoked([rERP['FRP_WORD'], rERP['MW=1'], rERP['WORD_MW=1']], weights=[1, 1,1])
            plot_conds = [
                ['FRP_MW=0','FRP_MW=1'],
                ['FRP_WORD_MW=0', 'FRP_WORD_MW=1'],
                ['FRP','FRP_WORD','FRP_STOP','FRP_PUNC'],
                ['surprisal_WORD','log_word_freq_WORD','relative_word_position_WORD'],
                ['surprisal_WORD_MW=0','surprisal_WORD_MW=1'],
                ['log_word_freq_WORD_MW=0','log_word_freq_WORD_MW=1'],
            ]
            fig, ax = plt.subplots(len(plot_conds), 1,figsize=(12, 9))
            for i,cc in enumerate(plot_conds):
            # rERP_group = mne.grand_average(rERP_ALL)
                plotdict = {k:rERP[k] for k in cc}
                mne.viz.plot_compare_evokeds(plotdict, picks='CPz', axes=ax[i] )
            fig.savefig(os.path.join(dir_out, f'{pID}_FRP_effects.png'))

            ##### save regression erps
            mne.write_evokeds(os.path.join(dir_out, f'{pID}_rERP-evk.fif'), [ev for ev in rERP.values()], overwrite=True)
            # append to list of all subjects
            rERP_ALL.append(rERP)
        # except Exception as e:
        #     print(f'Error in {pID}: {e}')
        #     traceback.print_exc()
        #     continue
           # save skip reasons
            skip_reasons = pd.Series(skip_reasons)
            skip_reasons.to_csv(os.path.join(dir_out, 'skip_reasons.csv'))
    pd.Series(skip_reasons).sort_index().to_csv(os.path.join(dir_out, 'skip_reasons.csv'))

    cond_counts_all = pd.DataFrame(cond_counts_all)
    cond_counts_all.to_csv(os.path.join(dir_out, 'cond_counts.csv'), index=False)

#%% read in already processed data
pIDs = [re.findall(r'EML1_\d{3}', f)[0] for f in os.listdir(dir_out) if f.endswith('_rERP-evk.fif')]
try:
    skip_reasons = pd.read_csv(os.path.join(dir_out, 'skip_reasons.csv'), index_col=0)
    skip_reasons = skip_reasons.fillna('')
    skip_reasons = skip_reasons.to_dict()['0']
except:
    skip_reasons = {}

#%% screen subjects comrpehension scores
comp_pat = ['Rote','Inf','Deep','SVT']
comp_nafc = [4, 2, 4, 3]

for pID in pIDs:
    skip_reasons[pID] = skip_reasons.get(pID, '')
    beh_df_i = beh_df[beh_df['ParticipantID']==pID]
    comp_scores=[]
    for pat in comp_pat:
        comp = beh_df_i.columns.str.contains(pat)
        comp_score = beh_df_i.loc[:,comp]
        comp_score = comp_score.melt(value_name='score').dropna()
        comp_score['nafc'] = comp_nafc[comp_pat.index(pat)]
        comp_scores.append(comp_score)
    comp_scores = pd.concat(comp_scores)
    pvals, res = comprehension_above_chance(comp_scores['score'].astype(int).values, comp_scores['nafc'].values)
    # print(f'{pID} combined weighted comprehension p-value: {res.pvalue:.3f}')
    if res.pvalue > 0.05:
        # print(f'!!!{pID} comprehension is not different from chance, skipping')
        skip_reasons[pID]+='|comprehension not different from chance|'
    MW = beh_df_i['MW'].mean()
    if MW < 0.1 or MW > 0.9:
        # print(f'!!!{pID} has {MW:.0%} MW, skipping')
        skip_reasons[pID]+=  '|MW outside 10-90%|'
    else:
        # print(f'{pID} has {MW:.0%} MW')
        pass

#%%
rERPs = {}
for pID in pIDs:
    rERP = mne.read_evokeds(os.path.join(dir_out, f'{pID}_rERP-evk.fif'))
    rERP={evk.comment:evk for evk in rERP}

    rERPs[pID] = rERP
    # get cond count
    for cond,c in rERP.items():
        if c.nave < 60:
            if ('WORD_MW=0' in cond or 'WORD_MW=1' in cond): 
                print(f'{pID} has only {c.nave} epochs for {cond}')
                skip_reasons[pID]+= f'|fewer than 60 fixations for {cond}|'

#%% exclusions
SKIP_N = True
SKIP_COMP = False
SKIP_MW = True

# check skip_reasons
if SKIP_N:
    pIDs_before = pIDs
    pIDs = [p for p in pIDs if 'fewer than' not in skip_reasons.get(p,'')]
    print(f'removed {len(pIDs_before)-len(pIDs)} subjects due to fewer than 60 fixations for a key condition')
if SKIP_COMP:
    pIDs_before = pIDs
    pIDs = [p for p in pIDs if 'comprehension not different from chance' not in skip_reasons.get(p,'')]
    print(f'removed {len(pIDs_before)-len(pIDs)} subjects due to comprehension not different from chance')
if SKIP_MW:
    pIDs_before = pIDs
    pIDs = [p for p in pIDs if 'MW outside 10-90%' not in skip_reasons.get(p,'')]
    print(f'removed {len(pIDs_before)-len(pIDs)} subjects due to MW outside 10-90%')
print(f'{len(pIDs)} subjects remaining after skipping')
# save skip reasons
skip_reasons = pd.Series(skip_reasons)
# skip_reasons.to_csv(os.path.join(dir_out, 'skip_reasons.csv'))


# %% reformat group results to a dict of condition keys and values is a list of evokeds one from each subject
rERP_ALL = {}
channels = ['CPz', 'FCz', 'AFF5h', 'AFF6h', 'CCP5h', 'CCP6h', 'PPO9h', 'PPO10h']
cond_combinations = {
    'ButtonPress':  ['reading/ButtonPress','sham/ButtonPress'],
    'FRP': 'reading/Fixation',
    'FRP_WORD': ['reading/Fixation','WORD'],
    'FRP_STOP': ['reading/Fixation','STOP'],
    'FRP_PUNC': ['reading/Fixation','PUNC'],
    'FRP_MW=0': ['reading/Fixation','MW=0'],
    'FRP_MW=1': ['reading/Fixation','MW=1'],
    'FRP_WORD_MW=0': ['WORD','MW=0','WORD_MW=0'],
    'FRP_WORD_MW=1': ['WORD','MW=1','WORD_MW=1'],
}
condnames = {}
for pID in pIDs:
    s = rERPs[pID]
    # refformat to dict of conditions
    for cond,c in s.items():
        condnames[cond] = cond
        # baseline correct
        c=c.apply_baseline((-.2, 0))
        # downsample to 100Hz
        c.resample(100)
        # check it contains CPz channel and skip if not
        if 'CPz' not in c.ch_names:
            print(f'{s} {cond} does not contain CPz, skipping')
            skip_reasons[pID] = f'does not contain CPz'
            pIDs.remove(pID)
            break

        if cond in rERP_ALL:
            rERP_ALL[cond].append(c)
        else:
            rERP_ALL[cond] = [c]
    # combo conditions using mne.combine_evoked
    for cc, clist in cond_combinations.items():
        # only combine if s contains all conditions
        clist = [c for c in clist if c in s]
        if not clist:
            print(f'{s} does not contain any conditions for {cc}')
            continue
        if len(clist) < len(cond_combinations[cc]):
            print(f'{s} does not contain all conditions for {cc}, will exclude missing conditions')
            continue
        res = mne.combine_evoked([s[ci] for ci in clist], weights=[1 for ci in clist])
        if cc in rERP_ALL:
            rERP_ALL[cc].append(res)
        else:
            rERP_ALL[cc] = [res]
#equalize channels 
for c in rERP_ALL:
    rERP_ALL[c]=mne.equalize_channels(rERP_ALL[c])

# combo conditions have annopying long names
condnames.update({k: ' + '.join([ vi for vi in v]) for k,v in cond_combinations.items()})


# %% t test on contrasts
contrast_conds =  [ 
        ['reading/Fixation','FRP_WORD'],
    ['WORD_MW=0','WORD_MW=1'],
    ['surprisal_WORD_MW=0','surprisal_WORD_MW=1'],
    ['log_word_freq_WORD_MW=0','log_word_freq_WORD_MW=1'],
    ['relative_word_position_WORD_MW=0','relative_word_position_WORD_MW=1'],
    'surprisal_WORD','log_word_freq_WORD','relative_word_position_WORD',
    'ButtonPress',
    'Blink'
                ]
channels = ['FCz','CPz',['AFF5h','AFF6h'],['CCP5h','CCP6h'],['PPO9h','PPO10h']]

for cc in contrast_conds:
    for ch in channels:
        if isinstance(ch, str):
            ch = [ch]
        if isinstance(cc, str) or len(cc) == 1:
            if isinstance(cc, str):
                cc = [cc]
                contrast_name = cc[0]
            x = [rERP.get_data(picks=ch) for rERP in rERP_ALL[cc[0]]]
            x = np.squeeze(np.array(x))

        elif len(cc) == 2:
            # X is list of array, shape (n_observations, p[, q][, r])
            x1 = np.array([rERP.get_data(picks=ch) for rERP in rERP_ALL[cc[0]]])
            x2 = np.array([rERP.get_data(picks=ch) for rERP in rERP_ALL[cc[1]]])
            x=np.squeeze(x2-x1)
            contrast_name = f'{cc[1]} - {cc[0]}'
        if len(x.shape)==3: # avg oevr channels
            x = np.mean(x, axis=1)
        T_obs, clusters, cluster_p_values, H0 = mne.stats.permutation_cluster_1samp_test(
                x, n_permutations=1000, seed=42, out_type='mask')  
        times = rERP_ALL[cc[0]][0].times
        fig, ax = plt.subplots()
        plotdict = {k:rERP_ALL[k] for k in cc}
        ax=plot_cluster(clusters, cluster_p_values,times, ax, tcfe=False)  
        # hold on 
        ax=mne.viz.plot_compare_evokeds(plotdict, picks=ch , axes=ax, combine='mean')
        fig.suptitle(f'Group-level {contrast_name}')
        fig.savefig(os.path.join(dir_out, f"Group_n=({len(pIDs)})_{contrast_name.replace('/','-')}_{'+'.join(ch)}.png"))

# %%
