# %%
import mne
import re
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
from datetime import date
import scipy.stats
from functools import partial
from mne_custom_regression import (
    ridge_regression_raw,
    ridge_model,
    plot_cluster,
    comprehension_above_chance,
    plot_evoked_joint
)
import seaborn as sns

sns.set_palette('tab10')

# get current dir to construct relative paths
dir_path = os.path.dirname(os.path.realpath(__file__))
os.chdir(dir_path)
pd.options.mode.chained_assignment = None  # default='warn'

#################
# same as v2d but with dropping first and last fixation on page
vnum = '12'
#################

# %% paths
dir_raw = '/Volumes/Blue1TB/EyeMindLink/Data'
dir_fif = '/Users/roso8920/Emotive Computing Dropbox/Rosy Southwell/EML Rosy/Data/EEG_processed/preprocessed_fif/'
event_fn_suffix = '_eyetracker_events.csv'  # inside dir_fif, events containing fixations sacs and blinks as well as tasks, generated by merge_eyetracker_eeg.py
dir_out_par = '/Users/roso8920/Emotive Computing Dropbox/Rosy Southwell/EML Rosy/Data/EEG_processed/'
REDO = False
FORCE_REDO = False
channels = ['CPz', 'FCz', 'AFF5h', 'AFF6h', 'CCP5h', 'CCP6h', 'PPO9h', 'PPO10h']
decimation = 1  # TODO: set to 1 for final pass analysis
ridge_alpha = 1
verstr = f'FRP_TRF_lexical_v{vnum}_alpha{ridge_alpha}_decim{decimation}'
dir_out = os.path.join(dir_out_par, verstr)


os.makedirs(dir_out, exist_ok=True)
dir_events = os.path.expanduser(
    '~/Emotive Computing Dropbox/Rosy Southwell/EyeMindLink/Processed/events/'
)  # task events
ia_df = pd.read_csv('../../info/ia_label_mapping_opt_surprisal.csv').rename(
    columns={'gpt2_surprisal_page': 'surprisal'}
)
# remove punctuation from IA_ID
ia_df = ia_df.loc[~ia_df['punctuation']]
ia_df['IA_ID'] = ia_df['IA_ID'].fillna('-1').astype(float).astype(int)
ia_df['log_word_freq'] = (
    ia_df['word_freq'].astype(float).apply(np.log).replace(-np.inf, np.nan)
)
# stop words have NA for surprisal and log_word_freq
ia_df.loc[ia_df['stop_word'], 'surprisal'] = np.nan
ia_df.loc[ia_df['stop_word'], 'log_word_freq'] = np.nan

beh_df = pd.read_csv(
    '~/Emotive Computing Dropbox/Rosy Southwell/EyeMindLink/Processed/Behaviour/EML1_page_level.csv'
)  # comp and MW scores
eeg_trigger_df = pd.read_csv('../../info/EEGtriggerSources.csv')
fn_base = '_p.fif'

pIDs = [
    re.findall(r'EML1_\d{3}', f)[0] for f in os.listdir(dir_fif) if f.endswith(fn_base)
]
# unique and sort
pIDs = sorted(list(set(pIDs)))
exclude = [20, 21, 22, 23, 24, 25, 26, 27, 31, 39, 40, 73, 77, 78, 87, 88, 93, 99, 
           110, 115, 123, 125, 138, 160, 164, 167, 168, 171, 172, 173, 177, 178, 179]  # ubj to exclude because no eeg or no trigger etc.
pIDs = [p for p in pIDs if int(re.findall(r'\d{3}', p)[0]) not in exclude]


channels = ['CPz', 'FCz', 'AFF5h', 'AFF6h', 'CCP5h', 'CCP6h', 'PPO9h', 'PPO10h']
#####
# pIDs = ['EML1_166'] #TMP
resume_from = 'EML1_145'
pIDs = pIDs[pIDs.index(resume_from):]
#####
# %% get today as a string

today = date.today()
today = today.strftime('%Y-%m-%d')
os.makedirs(os.path.join(dir_out, today), exist_ok=True)
def print_and_log(msg, log_fn):
    print(msg)
    with open(log_fn, 'a') as f:
        f.write(msg + '\n')
log_fn = os.path.join(dir_out, f'log_{today}.txt')
printlog = partial(print_and_log, log_fn=log_fn)

# %% Loop over subjects
if REDO:
    # initialize a text fiile for logging print statements
    with open(log_fn, 'w') as f:
        f.write('************\n')

    rERP_ALL = []
    for pID in pIDs:
        # try:
        # check if this pID already has a result
        if (
            os.path.exists(os.path.join(dir_out, f'{pID}_rERP-evk.fif'))
            and not FORCE_REDO
        ):
            printlog(f'{pID} already processed, skipping')
            continue
        printlog('\n')
        printlog(f'Processing {pID}')
        mne.set_log_level('ERROR')
        ##### load
        EEG = mne.io.read_raw_fif(os.path.join(dir_fif, f'{pID}_p.fif'), preload=True)
        # check all channels are present
        if set(channels).isdisjoint(EEG.ch_names):
            printlog(f'{pID} does not contain all channels, skipping')
            raise Exception(f'{pID} does not contain all channels, skipping')
        # check for bad channels and interpolate them
        if EEG.info['bads']:
            printlog(f'Interpolating bad channels {EEG.info["bads"]}')
            EEG.interpolate_bads()

        events = pd.read_csv(os.path.join(dir_fif, f'{pID}{event_fn_suffix}'))
 
        # treat '.' as missing in 'IA_ID'
        events['IA_ID'] = events['IA_ID'].replace('.', np.nan).fillna('-1').astype(int)
        if events['IA_ID'].nunique() == 1 and events['IA_ID'].unique()[0] == -1:
            printlog(f'{pID} has no IA_IDs, skipping')
            continue
        events['eeg_sample'] = events['eeg_sample'].astype(float).astype(int)
        # check if all events are from same eye, if not, keep only Right
        if not events['eye'].nunique() == 1:
            printlog(f'{pID} has events from both eyes, keeping only right')
            events = events[events['eye'] == 'R']
        # rename all fixations as Fixation regardless of eye
        events['event_type'] = events['event_type'].replace(
            'Fixation_R-reparsed', 'Fixation'
        )
        events['event_type'] = events['event_type'].replace(
            'Fixation_L-reparsed', 'Fixation'
        )
        events['event_type'] = events['event_type'].replace('Fixation_R', 'Fixation')
        events['event_type'] = events['event_type'].replace('Fixation_L', 'Fixation')

        events['identifier'] = events['identifier'].fillna('')  # some are NaN
        events['task'] = events['task'].fillna('none')  # some are NaN
        events['event_type'] = events['event_type'].fillna('other')  # some are NaN
        events = events.drop_duplicates(subset=['latency_sec', 'description'])
        beh_df_i = beh_df[beh_df['ParticipantID'] == pID]
        beh_df_i['identifier'] = beh_df_i['Text'].astype(str) + (
            beh_df_i['PageNum'] - 1
        ).astype(str)
        # merge lexical properties to events by IA_ID, which needs to be forced to be a string formatted as an integer not a float like 1.0
        events = events.merge(ia_df, how='left')
        events = events.merge(beh_df_i, how='left')
        events['task+type'] = events['task'] + '/' + events['event_type']
        # make annotations from events
        annot_all = mne.Annotations(
            onset=events['latency_sec'],
            duration=events['duration_sec'],
            description=events['task+type'],
        )
        EEG.set_annotations(annot_all)

        ##### apply preprocessing to EEG (interp bads and reref alraedy done)
        EEG.filter(0.5, 15)

        ##### select events
        # select only reading and sham for 'task'
        events = events[events['task'].str.contains('reading|sham')]
        fixations = events[events['event_type'].str.contains('Fixation')]
        blinks = events[events['event_type'].str.contains('Blink')]

        # remove first and last fixation on page (could be confounded by VEP, motor potentials and movement artefacts)
        fixations_by_page = fixations.groupby('identifier').agg(
            min_latency_sec = ('latency_sec','min'),
            max_latency_sec = ('latency_sec','max'),
            min_fix_pageIndex = ('fix_pageIndex','min'),
            max_fix_pageIndex = ('fix_pageIndex','max'),
        )
        len_bfore = len(fixations)
        # remove first and last fixation on page
        fixations = fixations.merge(fixations_by_page, how='left', on='identifier')
        fixations = fixations[
            (fixations['latency_sec'] > fixations['min_latency_sec'])
            & (fixations['latency_sec'] < fixations['max_latency_sec'])
            & (fixations['fix_pageIndex'] > fixations['min_fix_pageIndex'])
            & (fixations['fix_pageIndex'] < fixations['max_fix_pageIndex'])
        ]
        len_after = len(fixations)
        printlog(f'{pID} removed {len_bfore - len_after} fixations st start and end of page')
        # get sacc amp outliers for this participant as +- 3 STDEV from the mean INBOUND_SAC_AMPLITUDE
        sacc_amp_outliers = (
            np.abs(
                fixations['INBOUND_SAC_AMPLITUDE']
                - fixations['INBOUND_SAC_AMPLITUDE'].mean()
            )
            > 3 * fixations['INBOUND_SAC_AMPLITUDE'].std()
        )
        # drop fixations with extreme duration or saccade amplitude
        fixations = fixations[~sacc_amp_outliers]
        printlog(f'{pID} removed {sacc_amp_outliers.sum()} fixations with extreme saccade amplitude')   
        len_bfore = len(fixations)     
        # remove fixations with duration <50 or >1000
        fixations = fixations[
            (fixations['duration_sec'] > 0.05) & (fixations['duration_sec'] < 1)
        ]
        printlog(f'{pID} removed {len_bfore - len(fixations)} fixations with extreme duration')
        fixations = fixations.set_index('eeg_sample')

        annot_fix = mne.Annotations(
            onset=fixations['latency_sec'],
            duration=fixations['duration_sec'],
            description=fixations['task+type'],
        )
        EEG.set_annotations(annot_fix)
        trl_fix, trldict_fix = mne.events_from_annotations(EEG, regexp='.*Fixation')

        ##### MW
        fixations['MW'] = (
            fixations['MW'].fillna(-1).astype(int)
        )  # third condition coded as -1 for unknown
        # expand to dummy coded cols, one for MW=0 one for MW=1 (intercept is MW=-1)
        fixations['MW=0'] = (fixations['MW'] == 0).astype(int)
        fixations['MW=1'] = (fixations['MW'] == 1).astype(int)

        ##### covariates
        #  use latencies in trl to look up covariates in events
        lexical_covariates = ['surprisal', 'log_word_freq', 'relative_word_position']
        gaze_covariates = ['INBOUND_SAC_AMPLITUDE']
        cognitive_covariates = [
            'MW=0',
            'MW=1',
        ]

        ##### covariates
        # separate lexical covariates for MW and no MW fixations so we can look at interaction
        lexical_covariates_2 = []
        for l in lexical_covariates:
            for c in cognitive_covariates:
                fixations[f'{l}_{c}'] = np.where(
                    fixations[c] == 1, fixations[l], np.nan
                )
                lexical_covariates_2.append(f'{l}_{c}')
        lexical_covariates = lexical_covariates + lexical_covariates_2
        ##### add blinks
        blinks['task+type'] = 'Blink'
        blinks.set_index('eeg_sample', inplace=True)

        # concatenate covariate coplumns to fixations
        events_to_model = pd.concat([fixations, blinks])
        # take eeg_sample as a normal column again
        events_to_model.reset_index(inplace=True)
        # drop  duplicates on eeg sample taking into account decimation - GLM complains otherwise
        events_to_model['eeg_sample_decim'] = (
            events_to_model['eeg_sample'] / decimation
        ).astype(int)
        # check for duplicated event times on 'eeg_sample_decim'
        duplicates = events_to_model[
            events_to_model.duplicated(subset=['eeg_sample_decim'], keep=False)
        ]
        if duplicates.shape[0] > 0:
            printlog(f'{pID} has {duplicates.shape[0]} duplicates on eeg_sample_decim')
        # drop duplicates on eeg_sample_decim
        # but keep the last one (which is the blink)
            len_bfore = len(events_to_model)
            events_to_model = events_to_model.drop_duplicates(
            subset=['eeg_sample_decim'], keep='last'
            )  # blinks are way larger than fixations so priotise these
            printlog(f'removed duplicates: {len_bfore - len(events_to_model)}')
        # get covariates out of events now dupes have been droped
        covariates = events_to_model.loc[
            :, lexical_covariates + gaze_covariates + cognitive_covariates
        ]
        # scale and center copntinuous covariates (lex, gaze) but leave MW/refixations as is
        covariates.loc[:, lexical_covariates + gaze_covariates] = covariates.loc[
            :, lexical_covariates + gaze_covariates
        ].apply(lambda x: (x - x.mean()) / x.std(), axis=0)
        covariates = covariates.fillna(0)  # so equiv to mean over non nulls

        # trick to get trl and trldict
        annot_to_model = mne.Annotations(
            onset=events_to_model['latency_sec'],
            duration=events_to_model['duration_sec'],
            description=events_to_model['task+type'],
        )
        EEG.set_annotations(annot_to_model)
        trl_to_model, trldict_to_model = mne.events_from_annotations(
            EEG, regexp='.*Fixation|.*Blink'
        )

        ##### model
        tmin, tmax = -0.3, 0.8
        loglevelwas = mne.set_log_level('WARNING', return_old_level=True)
        try:
            X, rERP, stats = ridge_regression_raw(
                EEG,
                events=trl_to_model,
                event_id=trldict_to_model,
                tmin=tmin,
                tmax=tmax,
                reject={'eeg': 120e-6},  # uV, as in DImigen Ehinger 2019
                tstep=1,
                decim=decimation,  # TODO: replace w 1 when finalized
                covariates=covariates,
                model = partial(ridge_model, alpha=ridge_alpha),
                estimate_pvals=False,
            )
        except Exception as e:
            printlog(f'Error in fitting model for {pID}: {e}')
            continue
        ##### save stats
        save_fn = os.path.join(dir_out, f'{pID}_rERP_stats.npz')
        np.savez(save_fn, **stats)

        fig = rERP['reading/Fixation'].plot()
        fig.savefig(os.path.join(dir_out, f'{pID}_FRP_butterfly.png'))
        rERP['FRP_MW=0'] = mne.combine_evoked(
            [rERP['MW=0'], rERP['reading/Fixation']], weights=[1, 1]
        )
        rERP['FRP_MW=1'] = mne.combine_evoked(
            [rERP['MW=1'], rERP['reading/Fixation']], weights=[1, 1]
        )
        plot_conds = [
            ['FRP_MW=0', 'FRP_MW=1'],
            ['surprisal', 'log_word_freq', 'relative_word_position'],
            ['surprisal_MW=0', 'surprisal_MW=1'],
        ]
        fig, ax = plt.subplots(len(plot_conds), 1, figsize=(12, 9))
        for i, cc in enumerate(plot_conds):
            # rERP_group = mne.grand_average(rERP_ALL)
            plotdict = {k: rERP[k] for k in cc}
            mne.viz.plot_compare_evokeds(plotdict, picks='CPz', axes=ax[i])
        fig.savefig(os.path.join(dir_out, f'{pID}_FRP_effects.png'))

        ##### save regression erps
        mne.write_evokeds(
            os.path.join(dir_out, f'{pID}_rERP-evk.fif'),
            [ev for ev in rERP.values()],
            overwrite=True,
        )
        # append to list of all subjects
        rERP_ALL.append(rERP)
    # except Exception as e:
    #     printlog(f'Error in {pID}: {e}')
    #     traceback.print_exc()
    #     continue


# %% read in already processed data
pIDs = [
    re.findall(r'EML1_\d{3}', f)[0]
    for f in os.listdir(dir_out)
    if f.endswith('_rERP-evk.fif')
]
try:
    skip_reasons = pd.read_csv(os.path.join(dir_out, 'skip_reasons.csv'), index_col=0)
    skip_reasons = skip_reasons.fillna('')
    skip_reasons = skip_reasons.to_dict()['0']
except:
    skip_reasons = {}
# %% screen subjects comrpehension scores
comp_pat = ['Rote', 'Inf', 'Deep', 'SVT']
comp_nafc = [4, 2, 4, 3]

for pID in pIDs:
    skip_reasons[pID] = skip_reasons.get(pID, '')
    beh_df_i = beh_df[beh_df['ParticipantID'] == pID]
    comp_scores = []
    for pat in comp_pat:
        comp = beh_df_i.columns.str.contains(pat)
        comp_score = beh_df_i.loc[:, comp]
        comp_score = comp_score.melt(value_name='score').dropna()
        comp_score['nafc'] = comp_nafc[comp_pat.index(pat)]
        comp_scores.append(comp_score)
    comp_scores = pd.concat(comp_scores)
    pvals, res = comprehension_above_chance(
        comp_scores['score'].astype(int).values, comp_scores['nafc'].values
    )
    # printlog(f'{pID} combined weighted comprehension p-value: {res.pvalue:.3f}')
    if res.pvalue > 0.05:
        # printlog(f'!!!{pID} comprehension is not different from chance, skipping')
        skip_reasons[pID] += '|comprehension not different from chance|'
    MW = beh_df_i['MW'].mean()
    if MW < 0.1 or MW > 0.9:
        # printlog(f'!!!{pID} has {MW:.0%} MW, skipping')
        skip_reasons[pID] += '|MW outside 10-90%|'
    else:
        # printlog(f'{pID} has {MW:.0%} MW')
        pass


# %%
rERPs = {}
for pID in pIDs:
    rERP = mne.read_evokeds(
        os.path.join(dir_out, f'{pID}_rERP-evk.fif'), verbose='ERROR'
    )
    rERP = {evk.comment: evk for evk in rERP}

    rERPs[pID] = rERP
    # get cond count
    for cond, c in rERP.items():
        if c.nave < 60:
            if 'MW=0' in cond or 'MW=1' in cond:
                printlog(f'{pID} has only {c.nave} epochs for {cond}')
                skip_reasons[pID] += f'|fewer than 60 fixations for {cond}|'

# %% exclusions
SKIP_N = False
SKIP_COMP = False
SKIP_MW = True
# make a string for filenaming icorporating the three above
if not SKIP_N and not SKIP_COMP and not SKIP_MW:
    skip_str = '_noskip'
else:
    skip_str = '_skip'
    if SKIP_N:
        skip_str += 'N'
    if SKIP_COMP:
        skip_str += 'C'
    if SKIP_MW:
        skip_str += 'M'

# check skip_reasons
if SKIP_N:
    pIDs_before = pIDs
    pIDs = [p for p in pIDs if 'fewer than' not in skip_reasons.get(p, '')]
    printlog(
        f'removed {len(pIDs_before)-len(pIDs)} subjects due to fewer than 60 fixations for a key condition'
    )
if SKIP_COMP:
    pIDs_before = pIDs
    pIDs = [
        p
        for p in pIDs
        if 'comprehension not different from chance' not in skip_reasons.get(p, '')
    ]
    printlog(
        f'removed {len(pIDs_before)-len(pIDs)} subjects due to comprehension not different from chance'
    )
if SKIP_MW:
    pIDs_before = pIDs
    pIDs = [p for p in pIDs if 'MW outside' not in skip_reasons.get(p, '')]
    printlog(f'removed {len(pIDs_before)-len(pIDs)} subjects due to MW outside 10-90%')
printlog(f'{len(pIDs)} subjects remaining after skipping')
# save skip reasons
skip_reasons = pd.Series(skip_reasons)
skip_reasons.to_csv(os.path.join(dir_out, today, 'skip_reasons.csv'))

# %% reformat group results to a dict of condition keys and values is a list of evokeds one from each subject
rERP_ALL = {}
channels = ['CPz', 'FCz', 'AFF5h', 'AFF6h', 'CCP5h', 'CCP6h', 'PPO9h', 'PPO10h']
cond_combinations = {
    'Fixation': ['reading/Fixation', 'sham/Fixation'],
    'FRP_MW=0': ['reading/Fixation', 'MW=0'],
    'FRP_MW=1': ['reading/Fixation', 'MW=1'],

}
# sort pIDs
pIDs = sorted(pIDs, key=lambda x: int(re.findall(r'\d{3}', x)[0]))
condnames = {}
for pID in pIDs:
    print(pID)
    s = rERPs[pID]
    # refformat to dict of conditions
    for cond, c in s.items():
        condnames[cond] = cond
        # baseline correct
        c = c.apply_baseline((-0.1, 0), verbose='ERROR')
        # downsample to 100Hz
        c.resample(100, verbose='ERROR')
        # check it contains CPz channel and skip if not
        if 'CPz' not in c.ch_names:
            printlog(f'{s} {cond} does not contain CPz, skipping')
            skip_reasons[pID] = f'does not contain CPz'
            pIDs.remove(pID)
            break

        if cond in rERP_ALL:
            rERP_ALL[cond].append(c)
        else:
            rERP_ALL[cond] = [c]
    # combo conditions using mne.combine_evoked
    for cc, clist in cond_combinations.items():
        # only combine if s contains all conditions
        clist = [c for c in clist if c in s]
        if not clist:
            printlog(f'{s} does not contain any conditions for {cc}')
            continue
        if len(clist) < len(cond_combinations[cc]):
            printlog(
                f'{s} does not contain all conditions for {cc}, will exclude missing conditions'
            )
            continue
        res = mne.combine_evoked([s[ci] for ci in clist], weights=[1 for ci in clist])
        if cc in rERP_ALL:
            rERP_ALL[cc].append(res)
        else:
            rERP_ALL[cc] = [res]
# equalize channels
for c in rERP_ALL:
    rERP_ALL[c] = mne.equalize_channels(rERP_ALL[c])

# combo conditions have annopying long names
condnames.update(
    {k: ' + '.join([vi for vi in v]) for k, v in cond_combinations.items()}
)


# %% t test on contrasts
components = {'P1': {'latency': [70, 120],'channels':['PPO9h', 'PPO10h']}, 
            #    'N1':{'latency': [180, 220], 'channels':['CCP5h','PPO9h']},
              'P2': {'latency':[140, 220],'channels':['CPz', 'FCz']},
              'N400': {'latency':[250, 500],'channels':['CPz']},        # 300-500 is typical, Boudewyn use 300-600, Frank Aumestiere use 250-450
            #   'P600': {'latency':[500, 800],'channels':['CPz', 'FCz']}, 
}
# channels = ['CPz', 'FCz', 'AFF5h', 'AFF6h', 'CCP5h', 'CCP6h', 'PPO9h', 'PPO10h']
# ref: for latency see https://www.mdpi.com/2411-5150/4/1/11)
# P1: 70-120, occipital
# N1 component, a negative potential which is largest over left occipital, parietal and temporal areas of the scalp, with a peak approximately 200 ms after fixation onset.
# P2 P2 component has also been observed in several co-registration studies [106,109,113]. 
# This positive potential was observed first over anterior and central areas of the scalp between approximately 
# 140–280 ms after fixation onset, being modulated by parafoveal semantic relatedness [106] and word predictability [113], 
# and then later between approximately 200–280 ms over occipital scalp sites being modulated by parafoveal word form



contrast_conds = [
    'reading/Fixation',
    ['FRP_MW=0', 'FRP_MW=1'],
    'surprisal',
    'log_word_freq',
    'relative_word_position',
    ['surprisal_MW=0', 'surprisal_MW=1'],
    ['log_word_freq_MW=0', 'log_word_freq_MW=1'],
    ['relative_word_position_MW=0', 'relative_word_position_MW=1'],
    ['reading/Fixation', 'sham/Fixation'],
    'INBOUND_SAC_AMPLITUDE',
    'Blink'
]
channels = ['FCz','CPz','AFF5h','AFF6h','CCP5h','CCP6h','PPO9h','PPO10h']
times = rERP_ALL['reading/Fixation'][0].times

channels = ['CPz']
for cc in contrast_conds:
    printlog(f'\n\n\nContrast: {cc}')

    for ch in channels:
        if isinstance(ch, str):
            ch = [ch]
        if isinstance(cc, str) or len(cc) == 1:
            if isinstance(cc, str):
                cc = [cc]
                contrast_name = cc[0]
            x = [rERP.get_data(picks=ch) for rERP in rERP_ALL[cc[0]]]
            x = np.squeeze(np.array(x))
            ymax = np.max(np.abs(np.mean(x, axis=0)))
        elif len(cc) == 2:
            # X is list of array, shape (n_observations, p[, q][, r])
            x1 = np.array([rERP.get_data(picks=ch) for rERP in rERP_ALL[cc[0]]])
            x2 = np.array([rERP.get_data(picks=ch) for rERP in rERP_ALL[cc[1]]])
            x = np.squeeze(x2 - x1)
            contrast_name = f'{cc[1].replace("/"," - ")} - {cc[0].replace("/"," - ")}'
            # get max y val - average x over 1st dim
            ymax =np.max([np.abs(np.mean(x1, axis=0)), np.abs(np.mean(x2, axis=0))])
        if len(x.shape) == 3:  # avg oevr channels
            x = np.mean(x, axis=1)
        # T_obs, clusters, cluster_p_values, H0 = (
        #     mne.stats.permutation_cluster_1samp_test(x, n_permutations=10000, seed=42, out_type='mask'))

        # # write stats to csv
        # stats_fn = os.path.join(dir_out, today, f"{contrast_name.replace('/','-')}_{'+'.join(ch)}_stats.csv")
        # stats_df = pd.DataFrame({
        #         'times': np.round(rERP_ALL[cc[0]][0].times, 3),
        #         'T_obs': T_obs,
        #         'cluster_p_values': pd.NA,
        #     })
        # # set cluster p values column to corresponding cluster p values per time point
        # for i, c in enumerate(clusters):
        #     stats_df.loc[c[0], 'cluster_p_values'] = cluster_p_values[i]
        # stats_df.to_csv(stats_fn, index=False)

        # printlog(f'\n~~~Cluster-based stats for {contrast_name} at {ch}:')
        # if len(clusters) > 0:
        #     for i, c in enumerate(clusters):
        #         if cluster_p_values[i] < 0.05:
        #             printlog(f'{contrast_name} {ch}: {times[c][0]:.3f}-{times[c][-1]:.3f}s || *p={cluster_p_values[i]:.3f}*')
        #         else:   
        #             printlog(f'{contrast_name} {ch}: {times[c][0]:.3f}-{times[c][-1]:.3f}s || p={cluster_p_values[i]:.3f}')
        
        
        plotdict = {k: rERP_ALL[k] for k in cc}
        fig, ax1 = plt.subplots(1, 1, figsize=(6, 4), dpi=150)
        # fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(6, 6), dpi=150, sharex=True)
        # ax1 = plot_cluster(clusters, cluster_p_values, times, ax1, add_text=False)

        # Plot evokeds on ax1
        figs = mne.viz.plot_compare_evokeds(plotdict, picks=ch, axes=ax1, combine='mean')
        # set y label to au for continuous vars
        if any([v in contrast_name for v in ['surprisal', 'log_word_freq', 'relative_word_position','INBOUND_SAC_AMPLITUDE']]):
            ax1.set_ylabel('a.u.')

        # # Plot T_obs over time on ax2
        # ax2.plot(times, T_obs, color='k', label='T_obs')
        # t_crit = np.abs(scipy.stats.t.ppf(0.975, len(x)-1))  # one-tailed t-test critical value
        # ax2.axhline(0, color='k', linestyle='--', linewidth=0.5)
        # ax2.axhline(t_crit, color='r', linestyle='--', linewidth=0.5, label='t_crit')
        # ax2.axhline(-t_crit, color='r', linestyle='--', linewidth=0.5)
        # ax2.set_xlabel('Time (s)')
        # ax2.set_ylabel('T-value')
        fig.suptitle(f'Group-level {contrast_name}')
        fig.tight_layout()
        fig.savefig(os.path.join(dir_out, today, f"Group_n=({len(pIDs)}){skip_str}_{contrast_name.replace('/','-')}_{'+'.join(ch)}.png"))
        # save as editable vector graphics
        fig.savefig(os.path.join(
            dir_out, today, f"Group_n=({len(pIDs)}){skip_str}_{contrast_name.replace('/','-')}_{'+'.join(ch)}.pdf"
        ), format='pdf')
        ############ effects in predetermined time windows
    printlog(f'\n~~~ERP effects in predefined time windows:')
    for component_name, component_info in components.items():
        component_times = component_info['latency']
        component_channels = component_info['channels']
        comp_idx = np.where((times >= component_times[0]/1000) & (times <= component_times[1]/1000))[0]
        if len(cc) == 1:
            x = np.array([rERP.get_data(picks=component_channels) for rERP in rERP_ALL[cc[0]]])
        else:
            x1 = np.array([rERP.get_data(picks=component_channels) for rERP in rERP_ALL[cc[0]]])
            x2 = np.array([rERP.get_data(picks=component_channels) for rERP in rERP_ALL[cc[1]]])
            x = x2 - x1
        # avg over channels
        x = np.mean(x, axis=1)
        x = np.squeeze(x)
        # get mean amplitude in this window
        xc = x[:, comp_idx]
        # average over time dimension
        xc = np.mean(xc, axis=1)
        # t test
        T_comp, pval_comp = scipy.stats.ttest_1samp(xc,0)
        stars = ' * ' if pval_comp < 0.05 else '   '
        printlog(f'{stars}{contrast_name}@{component_name}: $t = {T_comp:.2f}$, $p = {pval_comp:.3f}$ {stars} (avg over predefined ERP window)')



    if len(cc) == 1:
        evk = mne.grand_average(plotdict[cc[0]])
        fix, ax = plt.subplots(1, 1, figsize=(6, 4), dpi=300)
        # fig = mne.viz.plot_evoked_joint(evk, picks=['eeg'], times='peaks', cmap='Dark2', exclude=[])
        fig = plot_evoked_joint(evk, picks=['eeg'], 
                                # times='peaks', 
                                times = [0,0.1,0.2,0.3, 0.4, 0.5],
                                cmap='Dark2', exclude=[], 
                                ts_args={'spatial_colors':False,'zorder':'std','show_names':True},
                                topomap_args={'cmap':'RdYlBu',  'show_names':True})

        fig.savefig(os.path.join(dir_out, today, f"Group_n=({len(pIDs)}){skip_str}_{contrast_name.replace('/','-')}_topo.png"))
        fig.savefig(os.path.join(dir_out, today, f"Group_n=({len(pIDs)}){skip_str}_{contrast_name.replace('/','-')}_topo.pdf"), format='pdf')

# %% coreelate the MW*surprisal beta with comprehension
beh_avg = beh_df.groupby('ParticipantID').mean(numeric_only=True).reset_index()
# make new column "compX' which is average of SVT, roteX, infX, deepX
beh_avg['compX'] = beh_avg[['Rote_X', 'Inference_X', 'Deep_X', 'SVT']].mean(axis=1)
for component_name, component_info in components.items():
    component_channels = component_info['channels']
    component_times = component_info['latency']
        # get the MW*surprisal beta
    x1 = np.array([rERP.get_data(picks=ch) for rERP in rERP_ALL['surprisal_MW=0']])
    x2 = np.array([rERP.get_data(picks=ch) for rERP in rERP_ALL['surprisal_MW=1']])
    pIDs_rERP = [rERP.comment for rERP in rERP_ALL['surprisal_MW=0']]
    x = x2 - x1
    comp_idx = np.where((times >= component_times[0]/1000) & (times <= component_times[1]/1000))[0]
    # avg over channels
    x = np.mean(x, axis=1)
    x = np.squeeze(x)
    # get mean amplitude in this window
    x = x[:, comp_idx]
    x = np.mean(x, axis=1)
    col_name = f'{component_name}_MWsurprisal'
    # Ensure pIDs_rERP is aligned with beh_avg
    col_to_add = pd.Series(x, index=pIDs)
    beh_avg[col_name] = beh_avg['ParticipantID'].map(col_to_add)
# drop columns that are na in components
beh_avg = beh_avg.dropna(subset=[f'{c}_MWsurprisal' for c in components.keys()])
# correls between each component and compX
for component_name in components.keys():
    col_name = f'{component_name}_MWsurprisal'
    r, p = scipy.stats.pearsonr(beh_avg[col_name], beh_avg['compX'])
    printlog(f'{col_name} vs compX: r={r:.2f}, p={p:.3f}')
# %%
