#%%
import mne
import re
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datetime import date

import glob
import os
import meegkit
from mne.datasets import sample
# from mne.stats.regression import linear_regression_raw
from sklearn.linear_model import Ridge
from sklearn.preprocessing import StandardScaler
import scipy
from functools import partial
from mne_custom_regression import ridge_regression_raw, ridge_model, plot_with_stats, plot_cluster, comprehension_above_chance
import seaborn as sns
sns.set_palette("tab10")
import traceback

# %% get current dir to construct relative paths
dir_path = os.path.dirname(os.path.realpath(__file__))
os.chdir(dir_path)
pd.options.mode.chained_assignment = None  # default='warn'
plt.ioff()

################################################
# just estimate FRP with no MW, lexical covariates, but model ALL fixations #
################################################



#%% paths
dir_raw = '/Volumes/Blue1TB/EyeMindLink/Data'
dir_fif = '/Volumes/Blue1TB/EEG_processed/preprocessed_fif/'
fn_base = '_p.fif'

pIDs = [re.findall(r'EML1_\d{3}', f)[0] for f in os.listdir(dir_fif) if f.endswith(fn_base)]
pIDs = sorted(list(set(pIDs)))
#####
resume_from = 'EML1_132'
pIDs = pIDs[pIDs.index(resume_from):]
#####
exclude = [20, 21, 22, 23, 24, 25, 26, 27, 30, 31, 32,  # 32 has too many bad epochs, none remain after criteria for rejection
           39, 40, 73, 77, 78, 87, 88, 93, 99,
           110, 115, 123, 125, 131,# 131 has too many bad epochs, none remain after criteria for rejection
             138, 160, 164, 167, 168, 171, 172, 173, 177, 178, 179]  # ubj to exclude because no eeg or no trigger etc.
pIDs = [p for p in pIDs if int(re.findall(r'\d{3}', p)[0]) not in exclude]

event_fn_suffix = '_eyetracker_events.csv' # inside dir_fif, events containing fixations sacs and blinks as well as tasks, generated by merge_eyetracker_eeg.py
dir_out_par = '/Volumes/Blue1TB/EEG_processed/'
REDO = True
FORCE_REDO = True
channels = ['CPz', 'FCz', 'AFF5h', 'AFF6h', 'CCP5h', 'CCP6h', 'PPO9h', 'PPO10h']
decimation = 10 #TODO: set to 1 for final pass analysis
ridge_alpha = 1
verstr = f'FRP_GLM_allfix_v2_decim{decimation}'
dir_out = os.path.join(dir_out_par, verstr)

os.makedirs(dir_out, exist_ok=True)
today = date.today()
today = today.strftime('%Y-%m-%d')
os.makedirs(os.path.join(dir_out, today), exist_ok=True)
def print_and_log(msg, log_fn):
    print(msg)
    with open(log_fn, 'a') as f:
        f.write(msg + '\n')
log_fn = os.path.join(dir_out, f'log_{today}.txt')
printlog = partial(print_and_log, log_fn=log_fn)
dir_events = os.path.expanduser('~/Emotive Computing Dropbox/Rosy Southwell/EyeMindLink/Processed/events/') # task events
ia_df = pd.read_csv('../../info/ia_label_mapping_opt_surprisal.csv').rename(columns={'gpt2_surprisal_page':'surprisal'})
# remove punctuation from IA_ID
ia_df = ia_df.loc[~ia_df['punctuation']]
ia_df['IA_ID'] = ia_df['IA_ID'].fillna('-1').astype(float).astype(int)
ia_df['log_word_freq'] = ia_df['word_freq'].astype(float).apply(np.log).replace(-np.inf, np.nan)

# stop words should have NA for surprisal and log_word_freq
ia_df.loc[ia_df['stop_word'], 'surprisal'] = np.nan
ia_df.loc[ia_df['stop_word'], 'log_word_freq'] = np.nan

beh_df = pd.read_csv('~/Emotive Computing Dropbox/Rosy Southwell/EyeMindLink/Processed/Behaviour/EML1_page_level.csv') # comp and MW scores
eeg_trigger_df = pd.read_csv('../../info/EEGtriggerSources.csv')

#%% Loop over subjects
skip_reasons = {}
if REDO:
    rERP_ALL = []
    for pID in pIDs: 
        # try:
            # check if this pID already has a result
            if os.path.exists(os.path.join(dir_out, f'{pID}_rERP-evk.fif')) and not FORCE_REDO:
                    print(f'{pID} already processed, skipping')
                    continue
            print('\n')
            print(f'Processing {pID}')
            mne.set_log_level('ERROR')
            ##### load 
            EEG = mne.io.read_raw_fif(os.path.join(dir_fif, f'{pID}_p.fif'), preload=True)
            # check all channels are present
            if set(channels).isdisjoint(EEG.ch_names):
                print(f'{pID} does not contain all channels, skipping')
                skip_reasons[pID] = 'missing channels'
                raise Exception(f'{pID} does not contain all channels, skipping')
            # check for bad channels and interpolate them
            if EEG.info['bads']:
                print(f'Interpolating bad channels {EEG.info["bads"]}')
                EEG.interpolate_bads()
            # triginfo = readtxtfile(fullfile(dir_fif, [pID '-info.txt']));
            with open(os.path.join(dir_fif, f'{pID}-info.txt')) as f:
                triginfo = f.read()
            task_events = pd.read_csv(os.path.join(dir_events, f'{pID}_events.csv')).rename(columns={'EVENT':'identifier','TrialType':'task'})
            # copy the correct EEGsample column for use depending on triginfo
            if 'LA0' in triginfo:
                task_events['eeg_sample'] = task_events['eegSD_sample_est'].astype(float).astype(int)
            else:
                task_events['eeg_sample'] = task_events['eeg_sample_est'].astype(float).astype(int)
            task_events['event_type'] = 'ButtonPress'
            # we want to model buttonpresses at the end of reading too, which are sometimes questions i.e. 'MW','SVT','Deep','Inference','Rote'
            task_events['task']=task_events['task'].fillna('other')
            task_events.loc[task_events['task'].str.contains('MW|SVT|Deep|Inference|Rote'), 'task'] = 'reading'
            task_events['latency_sec'] = task_events['eeg_sample']/EEG.info['sfreq']
            events = pd.read_csv(os.path.join(dir_fif, f'{pID}{event_fn_suffix}'))
            cols = ['event_type', 'task', 'identifier', 'description', 'eye', 'eeg_sample',
                'latency_sec', 'duration_sec', 
                'fix_pupilAvg', 'fix_pageIndex', 'IA_ID', 'IA_LABEL',
                'INBOUND_SAC_AMPLITUDE']
            task_events = task_events[[c for c in cols if c in task_events.columns]]
            events = pd.concat([events[cols], task_events])
            # treat '.' as missing in 'IA_ID'
            events['IA_ID'] = events['IA_ID'].replace('.', np.nan).fillna('-1').astype(int)
            # # give a different event type to fixations outside of IA
            # events.loc[(events['IA_ID']==-1 & events['event_type'].str.contains('Fixation')), 'event_type'] = 'FixationOutsideIA' 
            if events['IA_ID'].nunique()==1 and events['IA_ID'].unique()[0]==-1:
                print(f'{pID} has no IA_IDs, skipping')
                skip_reasons[pID] = 'no IA_IDs'
                continue
            events['eeg_sample'] = events['eeg_sample'].astype(float).astype(int)
            # check if all events are from same eye, if not, keep only Right
            if not events['eye'].nunique()==1:
                print(f'{pID} has events from both eyes, keeping only right')
                events = events[events['eye']=='R']
            # rename all fixations as Fixation regardless of eye
            events['event_type'] = events['event_type'].replace('Fixation_R-reparsed','Fixation')
            events['event_type'] = events['event_type'].replace('Fixation_L-reparsed','Fixation')
            events['event_type'] = events['event_type'].replace('Fixation_R','Fixation')
            events['event_type'] = events['event_type'].replace('Fixation_L','Fixation')

            events['identifier'] = events['identifier'].fillna('') # some are NaN
            events['task'] = events['task'].fillna('none') # some are NaN
            events['event_type'] = events['event_type'].fillna('other') # some are NaN
            events = events.drop_duplicates(subset=['latency_sec','description'])
           
            # merge lexical properties to events by IA_ID, which needs to be forced to be a string formatted as an integer not a float like 1.0
            events = events.merge(ia_df, how='left')
            events['task+type'] = events['task'] + '/' + events['event_type']
            # make annotations from events
            annot_all = mne.Annotations(onset=events['latency_sec'], duration=events['duration_sec'], description=events['task+type'])
            EEG.set_annotations(annot_all)

            ##### apply preprocessing to EEG (interp bads and reref alraedy done)
            EEG.filter(0.5, 15)

            ##### select events
            # select only reading 
            events = events[events['task'].str.contains('reading|sham')]
            fixations = events[events['event_type'].str.contains('Fixation') & events['task'].str.contains('reading')]
            sham_fixations = events[events['event_type'].str.contains('Fixation') & events['task'].str.contains('sham')]
            blinks = events[events['event_type'].str.contains('Blink')]
            task_events = events[events['event_type'].str.contains('ButtonPress')]

                    # remove first and last fixation on page (could be confounded by VEP, motor potentials and movement artefacts)
            fixations_by_page = fixations.groupby('identifier').agg(
                min_latency_sec = ('latency_sec','min'),
                max_latency_sec = ('latency_sec','max'),
                min_fix_pageIndex = ('fix_pageIndex','min'),
                max_fix_pageIndex = ('fix_pageIndex','max'),
            )
            len_bfore = len(fixations)
            # remove first and last fixation on page
            fixations = fixations.merge(fixations_by_page, how='left', on='identifier')
            fixations = fixations[
                (fixations['latency_sec'] > fixations['min_latency_sec'])
                & (fixations['latency_sec'] < fixations['max_latency_sec'])
                & (fixations['fix_pageIndex'] > fixations['min_fix_pageIndex'])
                & (fixations['fix_pageIndex'] < fixations['max_fix_pageIndex'])
            ]
            len_after = len(fixations)
            printlog(f'{pID} removed {len_bfore - len_after} fixations st start and end of page')
    
            # get sacc amp outliers for this participant as +- 3 STDEV from the mean INBOUND_SAC_AMPLITUDE
            sacc_amp_outliers = np.abs(fixations['INBOUND_SAC_AMPLITUDE'] - fixations['INBOUND_SAC_AMPLITUDE'].mean()) > 3*fixations['INBOUND_SAC_AMPLITUDE'].std()
            fixations['INBOUND_SAC_AMPLITUDE'] = fixations['INBOUND_SAC_AMPLITUDE'].fillna(0) 
            # drop fixations with extreme duration or saccade amplitude
            fixations = fixations[~sacc_amp_outliers]
            # remove fixations with duration <600ms (as per Caruso et al)
            fixations = fixations[(fixations['duration_sec'] > 0) & (fixations['duration_sec'] < .6)]
                  
            ##### covariates
            #  use latencies in trl to look up covariates in events
            fixations = fixations.set_index('eeg_sample')
 
            ##### add blinks 
            blinks['task+type'] = 'Blink'
            sham_fixations['task+type'] = 'sham/Fixation'
            task_events['task+type'] = 'ButtonPress'
            blinks.set_index('eeg_sample', inplace=True)
            task_events.set_index('eeg_sample', inplace=True)
            sham_fixations.set_index('eeg_sample', inplace=True)
            # concatenate covariate columns to fixations + task events
            events_to_model = pd.concat([fixations, sham_fixations, blinks, task_events])
            
            # take eeg_sample as a normal column again
            events_to_model.reset_index(inplace=True)
            # drop  duplicates on eeg sample taking into account decimation - GLM complains otherwise
            events_to_model['eeg_sample_decim'] = (events_to_model['eeg_sample']/decimation).astype(int)
            print(f'length before drop duplicates: {len(events_to_model)}')
    # check for duplicated event times on 'eeg_sample_decim'
            duplicates = events_to_model[
                events_to_model.duplicated(subset=['eeg_sample_decim'], keep=False)
            ]
            if duplicates.shape[0] > 0:
                printlog(f'{pID} has {duplicates.shape[0]} duplicates on eeg_sample_decim')
            # drop duplicates on eeg_sample_decim
            # but keep the last one (which is the blink)
                len_bfore = len(events_to_model)
                events_to_model = events_to_model.drop_duplicates(
                subset=['eeg_sample_decim'], keep='last'
                )  # blinks are way larger than fixations so priotise these
                printlog(f'removed duplicates: {len_bfore - len(events_to_model)}')
                 # trick to get trl and trldict 
            annot_to_model = mne.Annotations(onset=events_to_model['latency_sec'],
                                             duration=events_to_model['duration_sec'],
                                             description=events_to_model['task+type'])
            EEG.set_annotations(annot_to_model)
            trl_to_model, trldict_to_model = mne.events_from_annotations(EEG, regexp='.*Fixation*|.*Blink|.*ButtonPress')


            ##### model
            tmin, tmax = -0.3, 0.8
            loglevelwas = mne.set_log_level('WARNING', return_old_level=True)
            try:
                X, rERP, stats = ridge_regression_raw(
                    EEG, 
                    events=trl_to_model, event_id=trldict_to_model,
                    tmin=tmin, tmax=tmax, 
                    reject={'eeg': 120e-6}, # uV, as in DImigen Ehinger 2019
                    tstep=1,
                    decim=decimation, #TODO: replace w 1 when finalized
                    model = partial(ridge_model, alpha=ridge_alpha),
                    estimate_pvals=False
                )
            except Exception as e:
                printlog(f'Error in fitting model for {pID}: {e}')
                skip_reasons[pID] = 'model fitting error: ' + str(e)
                continue
            ##### save stats
            save_fn = os.path.join(dir_out, f'{pID}_rERP_stats.npz')
            np.savez(save_fn, **stats, X=X)

            ##### get residuals
            resid = stats['residuals']
            y_pred = stats['y_pred']
            # decomate events
            trl_decim = trl_to_model.copy()
            trl_decim[:, 0] -= EEG.first_samp
            trl_decim[:, 0] //= decimation       
            info = mne.create_info(ch_names=EEG.ch_names[0:len(channels)], sfreq=EEG.info['sfreq']//decimation, ch_types='eeg')
            y_pred_mne = mne.io.RawArray(y_pred.T, info)
            resid_mne = mne.io.RawArray(resid.T, info)
            # epock the residuals
            trldict_fix = {k:v for k,v in trldict_to_model.items() if 'reading/Fixation' in k}
            resid_epochs = mne.Epochs(resid_mne, trl_decim, event_id=trldict_fix, tmin=tmin, tmax=tmax, baseline=[-.1,0], 
            reject={'eeg': 120e-6}, preload=True)
            bad_epochs = resid_epochs.drop_log
            keep_ix = [i for i, b in enumerate(bad_epochs) if not b] # keep indices of good AND selected epochs
            keep_events = events_to_model.iloc[keep_ix]
            # add the beta for fixations to each epoch
            frp_dc_array = []
            rev_trldict = {v:k for k,v in trldict_to_model.items()}
            for ep in resid_epochs.iter_evoked():
                condition_ix = int(ep.comment)
                condition_name = rev_trldict[condition_ix]
                frp_est = rERP[condition_name]._data
                frp_dc_array.append(ep.data + frp_est)
            frp_dc_array = np.array(frp_dc_array)

            # continuous data estimated by removing the blink/buttonrpess predictors
            X_clean = X.copy()
            # set to 0 any regrerssor corresponding to blink or buttonrpess
            nuisance_vars = ['Blink', 'ButtonPress']
            nuisance_vars = [k for k in stats['regressor_indices'].keys() if any([nv in k for nv in nuisance_vars])]
            nuisance_ix = [stats['regressor_indices'][rv] for rv in nuisance_vars]
            # these are ranges, make a lsit of indices from ranges
            nuisance_ix = [i for ix in nuisance_ix for i in range(ix[0], ix[1])]
            # If X_clean is a scipy sparse matrix:
            for col in nuisance_ix:
                X_clean[:, col] = 0            
            # concatenate betas in the order given by regressor_indices
            beta_array = np.zeros((len(channels),X_clean.shape[1]))
            for evt,evix in stats['regressor_indices'].items():
                beta_array[:,evix[0]:evix[1]] = stats['betas'][evt]
            beta_array = beta_array.T
            y_pred_clean = X_clean @ beta_array # just blink and buttonpress events
            # add back resid
            y_pred_clean = y_pred_clean + resid
            # put into an MNE raw (just use a copy of EEG)
            y_pred_clean_mne = mne.io.RawArray(y_pred_clean.T, info)
            # save it
            y_pred_clean_mne.save(os.path.join(dir_out, f'{pID}_glmcleaned.fif'), overwrite=True)
            # # plot each epoch overlaif
            # fig, ax = plt.subplots(1,1, figsize=(12, 6))
            # for i, ep in enumerate(frp_dc_array):
            #     ep=np.squeeze(ep[0,:])
            #     ax.plot(ep, color='k', alpha=0.1)
            # # overplot the mean in thick red
            # ax.plot(np.mean(frp_dc_array[:,0,:],axis=0), color='r', linewidth=2)
            # plt.show()
            # fig.savefig(os.path.join(dir_out, f'{pID}_dcFRP_epochs.png'))
            ##### save events with dc FRP
            frp_info = keep_events.copy().reset_index(drop=True)
            for ch,channel in enumerate(channels):
                this_ch = frp_dc_array[:,ch,:]
                # check for nans in this channel
                if np.any(np.isnan(this_ch)):
                    print(f'dcFRP for {pID} {channel} has{np.sum(np.isnan(this_ch))} NaNs')
                    skip_reasons[pID] = 'NaNs in dcFRP'
                    continue
                # add col for each timepoint in this_ch
                this_ch_df = pd.DataFrame(this_ch, columns=[f'{channel}_{int(t*1000)}ms' for t in rERP['reading/Fixation'].times])
                # add the cols from this_ch_df to frp_info IGNORING INDEX
                frp_info = pd.concat([frp_info, this_ch_df], axis=1)
            frp_info.to_csv(os.path.join(dir_out, f'{pID}_dcFRP_epochs_allchannels.csv'))

            #####
            plot_conds = [
                ['reading/Fixation','sham/Fixation'],
                ['ButtonPress'],
                ['INBOUND_SAC_AMPLITUDE'],
                ['Blink'],
            ]
            fig, ax = plt.subplots(len(plot_conds), 1,figsize=(12, 9))
            for i,cc in enumerate(plot_conds):
                try:
                    plotdict = {k:rERP[k] for k in cc}
                    mne.viz.plot_compare_evokeds(plotdict, picks='CPz', axes=ax[i] )
                except KeyError as e:
                    print(f'Missing condition: {cc}')
            fig.savefig(os.path.join(dir_out, f'{pID}_FRP_effects.png'))

            ##### save regression erps
            mne.write_evokeds(os.path.join(dir_out, f'{pID}_rERP-evk.fif'), [ev for ev in rERP.values()], overwrite=True)
            # append to list of all subjects
            rERP_ALL.append(rERP)
        # except Exception as e:
        #     print(f'Error in {pID}: {e}')
        #     traceback.print_exc()
        #     continue
    pd.Series(skip_reasons).to_csv(os.path.join(dir_out, 'skip_reasons.csv'))







# %%
