#%%
import mne
import re
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import glob
import os
import meegkit
from mne.datasets import sample
# from mne.stats.regression import linear_regression_raw
from sklearn.linear_model import Ridge
from sklearn.preprocessing import StandardScaler
import scipy
from functools import partial
from mne_custom_regression import ridge_regression_raw, ridge_model, plot_with_stats, plot_cluster, comprehension_above_chance
import seaborn as sns
sns.set_palette("tab10")
import traceback
# get current dir to construct relative paths
dir_path = os.path.dirname(os.path.realpath(__file__))
os.chdir(dir_path)
pd.options.mode.chained_assignment = None  # default='warn'
#################
# 
vnum = '2c' 
#################
#%% paths
dir_raw = '/Volumes/Blue1TB/EyeMindLink/Data'
dir_fif = '/Volumes/Blue1TB/EEG_processed/preprocessed_fif/'
event_fn_suffix = '_eyetracker_events.csv' # inside dir_fif, events containing fixations sacs and blinks as well as tasks, generated by merge_eyetracker_eeg.py
dir_out_par = '/Volumes/Blue1TB/EEG_processed/'
REDO = False
FORCE_REDO = False
channels = ['CPz', 'FCz', 'AFF5h', 'AFF6h', 'CCP5h', 'CCP6h', 'PPO9h', 'PPO10h']
decimation = 10 #TODO: set to 1 for final pass analysis
ridge_alpha=1
verstr = f'FRP_TRF_lexical_v{vnum}_alpha{ridge_alpha}_decim{decimation}'
dir_out = os.path.join(dir_out_par, verstr)

# this version uses dummy coding for MW: intercept is FRP, MW=-1 and MW=0 are additional predictors
# there will be separate columsn for each MW and lexical covariate
# separate models for blink and saccade events too to remove them
# stricter prepro: filter, downsample
# infill covariates with 0 not mean
# remove fixations from the model if duration is extreme
# first pass and refixations separately too? 

os.makedirs(dir_out, exist_ok=True)
dir_events = os.path.expanduser('~/Emotive Computing Dropbox/Rosy Southwell/EyeMindLink/Processed/events/') # task events
ia_df = pd.read_csv('../info/ia_label_mapping_opt_surprisal.csv').rename(columns={'gpt2_surprisal_page':'surprisal'})
# remove punctuation from IA_ID
ia_df = ia_df.loc[~ia_df['punctuation']]
ia_df['IA_ID'] = ia_df['IA_ID'].fillna('-1').astype(float).astype(int)
ia_df['log_word_freq'] = ia_df['word_freq'].astype(float).apply(np.log).replace(-np.inf, np.nan)

beh_df = pd.read_csv('~/Emotive Computing Dropbox/Rosy Southwell/EyeMindLink/Processed/Behaviour/EML1_page_level.csv') # comp and MW scores
eeg_trigger_df = pd.read_csv('../info/EEGtriggerSources.csv')
fn_base = '_p.fif'

pIDs = [re.findall(r'EML1_\d{3}', f)[0] for f in os.listdir(dir_fif) if f.endswith(fn_base)]
# unique and sort
pIDs = sorted(list(set(pIDs)))
exclude = [20, 21, 22, 23, 24, 25, 26, 27, 30, 31, 39, 40, 73, 77, 78, 87,88,93,99, 
    110,115,123,125, 138, 160, 164,167,168, 171,172,173, 178,179] # ubj to exclude because no eeg or no trigger etc.
skip_reasons = {} if REDO else pd.read_csv(os.path.join(dir_out, 'skip_reasons.csv'), index_col=0).to_dict()['0']

skip_reasons = {f'EML1_{pID:03d}' : 'no eeg or no IAs' for pID in exclude}
pIDs = [p for p in pIDs if int(re.findall(r'\d{3}', p)[0]) not in exclude]


# #####
# pIDs = ['EML1_019', 'EML1_029', 'EML1_035', 'EML1_036', 'EML1_044', 'EML1_051', 'EML1_054', 'EML1_074', 'EML1_101', 'EML1_105', 'EML1_113', 'EML1_130', 'EML1_156', 'EML1_158', 'EML1_170', 'EML1_175', 'EML1_176', 'EML1_177']
resume_from = 'EML1_128'
pIDs = pIDs[pIDs.index(resume_from):]
# #####


#%% Loop over subjects
cond_counts_all = []
if REDO:
    rERP_ALL = []
    for pID in pIDs: 
        # try:
            # check if this pID already has a result
            if os.path.exists(os.path.join(dir_out, f'{pID}_rERP-evk.fif')) and not FORCE_REDO:
                    print(f'{pID} already processed, skipping')
                    continue
            print('\n')
            print(f'Processing {pID}')
            mne.set_log_level('ERROR')
            ##### load 
            EEG = mne.io.read_raw_fif(os.path.join(dir_fif, f'{pID}_p.fif'), preload=True)
            # check all channels are present
            if set(channels).isdisjoint(EEG.ch_names):
                print(f'{pID} does not contain all channels, skipping')
                skip_reasons[pID] = 'missing channels'

                raise Exception(f'{pID} does not contain all channels, skipping')
            # check for bad channels and interpolate them
            if EEG.info['bads']:
                print(f'Interpolating bad channels {EEG.info["bads"]}')
                EEG.interpolate_bads()
            
            events = pd.read_csv(os.path.join(dir_fif, f'{pID}{event_fn_suffix}'))
            # treat '.' as missing in 'IA_ID'
            events['IA_ID'] = events['IA_ID'].replace('.', np.nan).fillna('-1').astype(int)
            if events['IA_ID'].nunique()==1 and events['IA_ID'].unique()[0]==-1:
                print(f'{pID} has no IA_IDs, skipping')
                continue
            events['eeg_sample'] = events['eeg_sample'].astype(float).astype(int)
            # check if all events are from same eye, if not, keep only Right
            if not events['eye'].nunique()==1:
                print(f'{pID} has events from both eyes, keeping only right')
                events = events[events['eye']=='R']
            # rename all fixations as Fixation regardless of eye
            events['event_type'] = events['event_type'].replace('Fixation_R-reparsed','Fixation')
            events['event_type'] = events['event_type'].replace('Fixation_L-reparsed','Fixation')
            events['event_type'] = events['event_type'].replace('Fixation_R','Fixation')
            events['event_type'] = events['event_type'].replace('Fixation_L','Fixation')

            events['identifier'] = events['identifier'].fillna('') # some are NaN
            events['task'] = events['task'].fillna('none') # some are NaN
            events['event_type'] = events['event_type'].fillna('other') # some are NaN
            events = events.drop_duplicates(subset=['latency_sec','description'])
            beh_df_i = beh_df[beh_df['ParticipantID']==pID]
            beh_df_i['identifier'] = beh_df_i['Text'].astype(str) + (beh_df_i['PageNum']-1).astype(str)
            # merge lexical properties to events by IA_ID, which needs to be forced to be a string formatted as an integer not a float like 1.0
            events = events.merge(ia_df, how='left')
            events = events.merge(beh_df_i, how='left')
            events['task+type'] = events['task'] + '/' + events['event_type']
            # make annotations from events
            annot_all = mne.Annotations(onset=events['latency_sec'], duration=events['duration_sec'], description=events['task+type'])
            EEG.set_annotations(annot_all)


            ##### apply preprocessing to EEG (interp bads and reref alraedy done)
            EEG.filter(0.5, 15)

            ##### select events
            # select only reading and sham for 'task'
            events = events[events['task'].str.contains('reading|sham')]
            fixations = events[events['event_type'].str.contains('Fixation')]
            blinks = events[events['event_type'].str.contains('Blink')]
            # get sacc amp outliers for this participant as +- 3 STDEV from the mean INBOUND_SAC_AMPLITUDE
            sacc_amp_outliers = np.abs(fixations['INBOUND_SAC_AMPLITUDE'] - fixations['INBOUND_SAC_AMPLITUDE'].mean()) > 3*fixations['INBOUND_SAC_AMPLITUDE'].std()
            # drop fixations with extreme duration or saccade amplitude
            fixations = fixations[~sacc_amp_outliers]
            # remove fixations with duration <50 or >1000
            fixations = fixations[(fixations['duration_sec'] > 0.05) & (fixations['duration_sec'] < 1)]
            fixations = fixations.set_index('eeg_sample')

            annot_fix = mne.Annotations(onset=fixations['latency_sec'], duration=fixations['duration_sec'], description=fixations['task+type'])
            EEG.set_annotations(annot_fix)
            trl_fix, trldict_fix = mne.events_from_annotations(EEG, regexp='.*Fixation')

            ##### MW 
            fixations['MW'] = fixations['MW'].fillna(-1).astype(int) # third condition coded as -1 for unknown
            # expand to dummy coded cols, one for MW=0 one for MW=1 (intercept is MW=-1)
            fixations['MW=0'] = (fixations['MW']==0).astype(int)
            fixations['MW=1'] = (fixations['MW']==1).astype(int)

            ##### covariates
            #  use latencies in trl to look up covariates in events
            lexical_covariates = ['surprisal', 'log_word_freq', 'relative_word_position']
            gaze_covariates = ['INBOUND_SAC_AMPLITUDE']
            cognitive_covariates = ['MW=0','MW=1',
            ]

            ##### covariates
            # separate lexical covariates for MW and no MW fixations so we can look at interaction
            lexical_covariates_2 =[]
            for l in lexical_covariates:
                for c in cognitive_covariates:
                    fixations[f'{l}_{c}'] = np.where(fixations[c] == 1, fixations[l], np.nan)
                    lexical_covariates_2.append(f'{l}_{c}')
            lexical_covariates = lexical_covariates + lexical_covariates_2
            ##### add blinks 
            blinks['task+type'] = 'Blink'
            blinks.set_index('eeg_sample', inplace=True)
            # concatenate covariate coplumns to fixations
            events_to_model = pd.concat([fixations, blinks])
            # take eeg_sample as a normal column again
            events_to_model = events_to_model.sort_values('eeg_sample').reset_index()
            # drop  duplicates on eeg sample taking into account decimation - GLM complains otherwise
            events_to_model['eeg_sample_decim'] = (events_to_model['eeg_sample']/decimation).astype(int)
            print(f'length before drop duplicates: {len(events_to_model)}')
            events_to_model = events_to_model.drop_duplicates(subset=['eeg_sample_decim'], keep='first')
            print(f'length after drop duplicates: {len(events_to_model)}')
            # get covariates out of events now dupes have been droped
            covariates = events_to_model.loc[:,['eeg_sample']+lexical_covariates+gaze_covariates+cognitive_covariates]
            # scale and center copntinuous covariates (lex, gaze) but leave MW/refixations as is
            covariates.loc[:,lexical_covariates+gaze_covariates] = covariates.loc[:,lexical_covariates+gaze_covariates].apply(lambda x: (x-x.mean())/x.std(), axis=0)
            covariates = covariates.fillna(0) # so equiv to mean over non nulls

            # trick to get trl and trldict 
            annot_to_model = mne.Annotations(onset=events_to_model['latency_sec'], 
                                             duration=events_to_model['duration_sec'], 
                                             description=events_to_model['task+type'])            
            EEG.set_annotations(annot_to_model)
            trl_to_model, trldict_to_model = mne.events_from_annotations(EEG, regexp='.*Fixation|.*Blink')
            # check covariates same length as trl 
            if len(covariates) != len(trl_to_model):
                print(f'{pID} covariates and trl are different lengths')
                # get matching eeg_samples from trl first column and coviarates eeg_sample
                trl_eeg_samples = trl_to_model[:,0]
                cov_eeg_samples = covariates['eeg_sample']
                common = np.intersect1d(trl_eeg_samples, cov_eeg_samples)
                covariates = covariates[covariates['eeg_sample'].isin(common)]
                trl_to_model = trl_to_model[np.isin(trl_to_model[:,0], common)]
            # check if covariates is singular
            if np.linalg.matrix_rank(covariates) < covariates.shape[1]:
                print(f'{pID} covariates are singular')
                skip_reasons[pID] = 'singular covariates'
                continue
            
            ##### count fixations per categorical condition
            cond_counts = {}
            for cond in ['MW=0','MW=1']:
                cond_counts[cond] = (events_to_model[cond]).sum()
                if cond_counts[cond] < 60:
                    print(f'{pID} has fewer than 60 fixations in condition {cond}')
                    skip_reasons[pID] = 'fewer than 60 fixations per condition'
            cond_counts['FixationWord'] = (events_to_model['task+type'].str.contains('FixationWord').sum())
            cond_counts['pID'] = pID
            cond_counts_all.append(cond_counts)
            ##### model
            tmin, tmax = -0.3, 0.8
            loglevelwas = mne.set_log_level('WARNING', return_old_level=True)
            try:
                X, rERP, stats = ridge_regression_raw(
                    EEG, 
                    events=trl_to_model, event_id=trldict_to_model,
                    tmin=tmin, tmax=tmax, 
                    reject={'eeg': 120e-6}, # uV, as in DImigen Ehinger 2019
                    tstep=1,
                    decim=decimation, #TODO: replace w 1 when finalized
                    covariates=covariates.drop(columns=['eeg_sample']), 
                    model = partial(ridge_model, alpha=ridge_alpha),
                    estimate_stats=False
                )
            except Exception as e:
                print(f'Error in fitting model for {pID}: {e}')
                skip_reasons[pID] = 'model fitting error: ' + str(e)
                continue
            ##### save stats
            save_fn = os.path.join(dir_out, f'{pID}_rERP_stats.npz')
            np.savez(save_fn, **stats)
            # #### visualise significant effects
            # # plot p-values on evokeds
            # plotconds = ['reading/Fixation','sham/Fixation','MW=0','MW=1','surprisal','log_word_freq','relative_word_position']
            # fig, ax = plt.subplots(len(plotconds),1, figsize=(12, 12))
            # for i,cond in enumerate(plotconds):
            #     evk = rERP[cond]
            #     condname = evk.comment
            #     pvals = stats['p-values'][cond]
            #     plot_with_stats(evk, pvals, channel='CPz', ax=ax[i])
            #     # set title of axis to cond
            #     ax[i].set_title(cond)
            # fig.savefig(os.path.join(dir_out, f'{pID}_pvals.png'))

            ##### plot contrast between MW and no MW for main effect 
            fig=rERP['reading/Fixation'].plot()
            fig.savefig(os.path.join(dir_out, f'{pID}_FRP_butterfly.png'))
            rERP['FRP_MW=0'] = mne.combine_evoked([rERP['MW=0'], rERP['reading/Fixation']], weights=[1, 1])
            rERP['FRP_MW=1'] = mne.combine_evoked([rERP['MW=1'], rERP['reading/Fixation']], weights=[1, 1])
            plot_conds = [
                ['FRP_MW=0','FRP_MW=1'],
                ['surprisal','log_word_freq','relative_word_position'],
                ['surprisal_MW=0','surprisal_MW=1'],
            ]
            fig, ax = plt.subplots(len(plot_conds), 1,figsize=(12, 9))
            for i,cc in enumerate(plot_conds):
            # rERP_group = mne.grand_average(rERP_ALL)
                plotdict = {k:rERP[k] for k in cc}
                mne.viz.plot_compare_evokeds(plotdict, picks='CPz', axes=ax[i] )
            fig.savefig(os.path.join(dir_out, f'{pID}_FRP_effects.png'))

            ##### save regression erps
            mne.write_evokeds(os.path.join(dir_out, f'{pID}_rERP-evk.fif'), [ev for ev in rERP.values()], overwrite=True)
            # append to list of all subjects
            rERP_ALL.append(rERP)
        # except Exception as e:
        #     print(f'Error in {pID}: {e}')
        #     traceback.print_exc()
        #     continue

#%% read in already processed data
pIDs = [re.findall(r'EML1_\d{3}', f)[0] for f in os.listdir(dir_out) if f.endswith('_rERP-evk.fif')]
pIDs = ['EML1_028',
 'EML1_032',
 'EML1_034',
 'EML1_037',
 'EML1_038',
 'EML1_041',
 'EML1_042',
 'EML1_043',
 'EML1_045',
 'EML1_046',
 'EML1_047',
 'EML1_048',
 'EML1_049',
 'EML1_050',
 'EML1_052',
 'EML1_053',
 'EML1_055',
 'EML1_056',
 'EML1_058',
 'EML1_059',
 'EML1_060',
 'EML1_061',
 'EML1_062',
 'EML1_063',
 'EML1_064',
 'EML1_065',
 'EML1_066',
 'EML1_067',
 'EML1_068',
 'EML1_069',
 'EML1_070',
 'EML1_071',
 'EML1_072',
 'EML1_075',
 'EML1_076',
 'EML1_080',
 'EML1_081',
 'EML1_082',
 'EML1_083',
 'EML1_085',
 'EML1_089',
 'EML1_090',
 'EML1_091',
 'EML1_094',
 'EML1_095',
 'EML1_096',
 'EML1_097',
 'EML1_098',
 'EML1_100',
 'EML1_102',
 'EML1_103',
 'EML1_104',
 'EML1_106',
 'EML1_107',
 'EML1_108',
 'EML1_109',
 'EML1_111',
 'EML1_112',
 'EML1_114',
 'EML1_116',
 'EML1_117',
 'EML1_118',
 'EML1_119',
 'EML1_120',
 'EML1_121',
 'EML1_122',
 'EML1_124',
 'EML1_126',
 'EML1_128',
 'EML1_131',
 'EML1_132',
 'EML1_133',
 'EML1_134',
 'EML1_135',
 'EML1_136',
 'EML1_137',
 'EML1_139',
 'EML1_140',
 'EML1_141',
 'EML1_142',
 'EML1_143',
 'EML1_144',
 'EML1_145',
 'EML1_146',
 'EML1_147',
 'EML1_148',
 'EML1_149',
 'EML1_150',
 'EML1_151',
 'EML1_153',
 'EML1_154',
 'EML1_155',
 'EML1_157',
 'EML1_161',
 'EML1_162',
 'EML1_163',
 'EML1_165',
 'EML1_166',
 'EML1_169',
 'EML1_181']
try:
    skip_reasons = pd.read_csv(os.path.join(dir_out, 'skip_reasons.csv'), index_col=0).to_dict()['0']
except:
    skip_reasons = {}
#%% screen subjects comrpehension scores
comp_pat = ['Rote','Inf','Deep','SVT']
comp_nafc = [4, 2, 4, 3]
pIDs_before = pIDs
pIDs_remove_MW = []
pIDs_remove_chance = []
for pID in pIDs:
    beh_df_i = beh_df[beh_df['ParticipantID']==pID]
    comp_scores=[]
    # print(f'\n----pID: {pID}----')
    for pat in comp_pat:
        comp = beh_df_i.columns.str.contains(pat)
        comp_score = beh_df_i.loc[:,comp]
        # pivot longer
        comp_score = comp_score.melt(value_name='score').dropna()
        comp_score['nafc'] = comp_nafc[comp_pat.index(pat)]
        comp_scores.append(comp_score)
    comp_scores = pd.concat(comp_scores)
    pvals, res = comprehension_above_chance(comp_scores['score'].astype(int).values, comp_scores['nafc'].values)
    print(f'{pID} combined weighted comprehension p-value: {res.pvalue:.3f}')
    if res.pvalue > 0.05:
        # print(f'!!!{pID} comprehension is not different from chance, skipping')
        skip_reasons[pID] = 'comprehension not different from chance'
        pIDs_remove_chance.append(pID)
    # check % MW
    MW = beh_df_i['MW'].mean()
    if MW < 0.1 or MW > 0.9:
        # print(f'!!!{pID} has {MW:.0%} MW, skipping')
        skip_reasons[pID] =  'MW outside 10-90%'
        pIDs_remove_MW.append(pID)
    else:
        pass
        # print(f'{pID} has {MW:.0%} MW')
# pIDs_remove = pIDs_remove_MW + pIDs_remove_chance
# pIDs = [p for p in pIDs if p not in pIDs_remove]
# print(f'\n\n---{len(pIDs)} subjects remaining after removing {len(pIDs_remove_chance)} due to chance performance and {len(pIDs_remove_MW)} imbalanced MW scores---')
# print(f'removed the following subjects: {", ".join(pIDs_remove)}')
skip_reasons = pd.Series(skip_reasons)
skip_reasons.to_csv(os.path.join(dir_out, 'skip_reasons.csv'))

# %% exclusions
SKIP_N = False
SKIP_COMP = False
SKIP_MW = False

# load skip_reasons
if SKIP_N:
    pIDs_before = pIDs
    pIDs = [p for p in pIDs if skip_reasons.get(p,'') != 'fewer than 60 fixations per condition (MW*REFIXATION)']
    print(f'removed {len(pIDs_before)-len(pIDs)} subjects due to fewer than 60 fixations per condition (MW*REFIXATION)')
if SKIP_COMP:
    pIDs_before = pIDs
    pIDs = [p for p in pIDs if skip_reasons.get(p,'')!= 'comprehension not different from chance']
    print(f'removed {len(pIDs_before)-len(pIDs)} subjects due to comprehension not different from chance')
if SKIP_MW:
    pIDs_before = pIDs
    pIDs = [p for p in pIDs if skip_reasons.get(p,'') != 'MW outside 10-90%']
    print(f'removed {len(pIDs_before)-len(pIDs)} subjects due to MW outside 10-90%')
print(f'{len(pIDs)} subjects remaining after skipping')

# %%
rERP_list = []
for pID in pIDs:
    rERP = mne.read_evokeds(os.path.join(dir_out, f'{pID}_rERP-evk.fif'))
    rERP_list.append(rERP)
# group average and stats
# reformat group results to a dict of condition keys and values is a list of evokeds one from each subject
rERP_ALL = {}
channels = ['CPz', 'FCz', 'AFF5h', 'AFF6h', 'CCP5h', 'CCP6h', 'PPO9h', 'PPO10h']
# cond_combinations = {
#     'reading/Fixation': ['reading/Fixation/MW=-1','reading/Fixation/MW=0', 'reading/Fixation/MW=1'],
#     'surprisal': ['surprisal_MW=-1','surprisal_MW=0', 'surprisal_MW=1'],
#     'word_freq': ['word_freq_MW=-1','word_freq_MW=0', 'word_freq_MW=1'],
#     'relative_word_position': ['relative_word_position_MW=-1','relative_word_position_MW=0', 'relative_word_position_MW=1'],
# }
cond_combinations = {
    'Fixation' : ['reading/Fixation','sham/Fixation'],
    'FRP': ['reading/Fixation'],
    'FRP_MW=0': ['reading/Fixation','MW=0'],
    'FRP_MW=1': ['reading/Fixation','MW=1'], 
}
condnames = {}
for s in rERP_list:
    # refformat to dict of conditions
    s={evk.comment:evk for evk in s}
    for cond,c in s.items():
        condnames[cond] = cond
        # baseline correct
        c=c.apply_baseline((-.1, 0))
        # downsample to 100Hz
        c.resample(100)
        # check it contains CPz channel and skip if not
        if 'CPz' not in c.ch_names:
            print(f'{s} does not contain CPz, skipping')
            continue
        if cond in rERP_ALL:
            rERP_ALL[cond].append(c)
        else:
            rERP_ALL[cond] = [c]
    # combo conditions using mne.combine_evoked
    for cc, clist in cond_combinations.items():
        res = mne.combine_evoked([s[ci] for ci in clist], weights=[1 for ci in clist])
        if cc in rERP_ALL:
            rERP_ALL[cc].append(res)
        else:
            rERP_ALL[cc] = [res]
#equalize channels 
for c in rERP_ALL:
    rERP_ALL[c]=mne.equalize_channels(rERP_ALL[c])

# combo conditions have annopying long names
condnames.update({k: ' + '.join([ vi for vi in v]) for k,v in cond_combinations.items()})

# %% t test on contrasts
contrast_conds =  [ 
    'FRP',
    ['FRP_MW=0','FRP_MW=1'],
                ['surprisal_MW=0','surprisal_MW=1'],
                ['log_word_freq_MW=0','log_word_freq_MW=1'],
                ['relative_word_position_MW=0','relative_word_position_MW=1'],
    'surprisal','log_word_freq','relative_word_position',
    ['reading/Fixation','sham/Fixation'],
    'INBOUND_SAC_AMPLITUDE',
                ]
channels = ['CPz']

for cc in contrast_conds:
    for ch in channels:
        if isinstance(ch, str):
            ch = [ch]
        if isinstance(cc, str) or len(cc) == 1:
            if isinstance(cc, str):
                cc = [cc]
                contrast_name = cc[0]
            x = [rERP.get_data(picks=ch) for rERP in rERP_ALL[cc[0]]]
            x = np.squeeze(np.array(x))

        elif len(cc) == 2:
            # X is list of array, shape (n_observations, p[, q][, r])
            x1 = np.array([rERP.get_data(picks=ch) for rERP in rERP_ALL[cc[0]]])
            x2 = np.array([rERP.get_data(picks=ch) for rERP in rERP_ALL[cc[1]]])
            x=np.squeeze(x2-x1)
            contrast_name = f'{cc[1]} - {cc[0]}'
        if len(x.shape)==3: # avg oevr channels
            x = np.mean(x, axis=1)
        T_obs, clusters, cluster_p_values, H0 = mne.stats.permutation_cluster_1samp_test(
                x, n_permutations=1000, seed=42, out_type='mask')  
        times = rERP_ALL[cc[0]][0].times
        fig, ax = plt.subplots()
        plotdict = {k:rERP_ALL[k] for k in cc}
        ax=plot_cluster(clusters, cluster_p_values,times, ax, tcfe=False)  
        # hold on 
        ax=mne.viz.plot_compare_evokeds(plotdict, picks=ch , axes=ax, combine='mean')
        fig.suptitle(f'Group-level {contrast_name}')
        fig.savefig(os.path.join(dir_out, f"Group_n=({len(rERP_list)})_{contrast_name.replace('/','-')}_{'+'.join(ch)}.png"))
    if len(cc) == 1:
        evk = mne.grand_average(plotdict[cc[0]])
        fig=mne.viz.plot_evoked_joint(evk, picks=['eeg'], times='peaks',exclude=[])
        fig.savefig(os.path.join(dir_out, f"Group_n=({len(rERP_list)})_{contrast_name.replace('/','-')}_topo.png"))


# %%
