#%%
import mne
import re
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import glob
import os
import meegkit
from mne.datasets import sample
# from mne.stats.regression import linear_regression_raw
from sklearn.linear_model import Ridge
from sklearn.preprocessing import StandardScaler
import scipy
from functools import partial
from mne_custom_regression import ridge_regression_raw, ridge_model, plot_with_stats, plot_cluster, comprehension_above_chance
import seaborn as sns
sns.set_palette("tab10")
import traceback
# get current dir to construct relative paths
dir_path = os.path.dirname(os.path.realpath(__file__))
os.chdir(dir_path)
pd.options.mode.chained_assignment = None  # default='warn'

#%% paths
dir_raw = '/Volumes/Blue1TB/EyeMindLink/Data'
dir_fif = '/Volumes/Blue1TB/EEG_processed/preprocessed_fif/'
event_fn_suffix = '_eyetracker_events.csv' # inside dir_fif, events containing fixations sacs and blinks as well as tasks, generated by merge_eyetracker_eeg.py
dir_out = '/Volumes/Blue1TB/EEG_processed/FRP_TRF_lexical_v2_rerun4'
# this version is just plotting code, allowing fro debugging whether participant exclusion/plotting code is responsible for differences between pipelines
#exclusions
SKIP_N = False
SKIP_COMP = False
SKIP_MW = False
# make a string for filenaming icorporating the three above
if not SKIP_N and not SKIP_COMP and not SKIP_MW:
    skip_str = '_noskip'
else:
    skip_str = '_skip'
    if SKIP_N:
        skip_str += 'N'
    if SKIP_COMP:
        skip_str += 'C'
    if SKIP_MW:
        skip_str += 'M'


os.makedirs(dir_out, exist_ok=True)
dir_events = os.path.expanduser('~/Emotive Computing Dropbox/Rosy Southwell/EyeMindLink/Processed/events/') # task events
ia_df = pd.read_csv('../info/ia_label_mapping_opt_surprisal.csv').rename(columns={'gpt2_surprisal_page':'surprisal'})
# remove punctuation from IA_ID
ia_df = ia_df.loc[~ia_df['punctuation']]
ia_df['IA_ID'] = ia_df['IA_ID'].fillna('-1').astype(float).astype(int)
ia_df['log_word_freq'] = ia_df['word_freq'].astype(float).apply(np.log).replace(-np.inf, np.nan)

beh_df = pd.read_csv('~/Emotive Computing Dropbox/Rosy Southwell/EyeMindLink/Processed/Behaviour/EML1_page_level.csv') # comp and MW scores
eeg_trigger_df = pd.read_csv('../info/EEGtriggerSources.csv')
fn_base = '_p.fif'

channels = ['CPz', 'FCz', 'AFF5h', 'AFF6h', 'CCP5h', 'CCP6h', 'PPO9h', 'PPO10h']
decimation = 10
# #####
# pIDs = [ 'EML1_177'] #TMP
# resume_from = 'EML1_148'
# pIDs = pIDs[pIDs.index(resume_from):]
# #####

# %% get today as a string
from datetime import date
today = date.today()
today = today.strftime("%Y-%m-%d")
os.makedirs(os.path.join(dir_out, today), exist_ok=True)
#%% read in already processed data
pIDs = [re.findall(r'EML1_\d{3}', f)[0] for f in os.listdir(dir_out) if f.endswith('_rERP-evk.fif')]
try:
    skip_reasons = pd.read_csv(os.path.join(dir_out,today, 'skip_reasons.csv'), index_col=0)
    skip_reasons = skip_reasons.fillna('')
    skip_reasons = skip_reasons.to_dict()['0']
except:
    skip_reasons = {}
#%% screen subjects comrpehension scores
comp_pat = ['Rote','Inf','Deep','SVT']
comp_nafc = [4, 2, 4, 3]

for pID in pIDs:
    skip_reasons[pID] = skip_reasons.get(pID, '')
    beh_df_i = beh_df[beh_df['ParticipantID']==pID]
    comp_scores=[]
    for pat in comp_pat:
        comp = beh_df_i.columns.str.contains(pat)
        comp_score = beh_df_i.loc[:,comp]
        comp_score = comp_score.melt(value_name='score').dropna()
        comp_score['nafc'] = comp_nafc[comp_pat.index(pat)]
        comp_scores.append(comp_score)
    comp_scores = pd.concat(comp_scores)
    pvals, res = comprehension_above_chance(comp_scores['score'].astype(int).values, comp_scores['nafc'].values)
    # print(f'{pID} combined weighted comprehension p-value: {res.pvalue:.3f}')
    if res.pvalue > 0.05:
        # print(f'!!!{pID} comprehension is not different from chance, skipping')
        skip_reasons[pID]+='|comprehension not different from chance|'
    MW = beh_df_i['MW'].mean()
    if MW < 0.2 or MW > 0.8:
        # print(f'!!!{pID} has {MW:.0%} MW, skipping')
        skip_reasons[pID]+=  '|MW outside 20-80%|'
    else:
        # print(f'{pID} has {MW:.0%} MW')
        pass


#%%
rERPs = {}
for pID in pIDs:
    rERP = mne.read_evokeds(os.path.join(dir_out, f'{pID}_rERP-evk.fif'), verbose='ERROR')
    rERP={evk.comment:evk for evk in rERP}

    rERPs[pID] = rERP
    # get cond count
    for cond,c in rERP.items():
        if c.nave < 60:
            if ('MW=0' in cond or 'MW=1' in cond): 
                print(f'{pID} has only {c.nave} epochs for {cond}')
                skip_reasons[pID]+= f'|fewer than 60 fixations for {cond}|'


# check skip_reasons
if SKIP_N:
    pIDs_before = pIDs
    pIDs = [p for p in pIDs if 'fewer than' not in skip_reasons.get(p,'')]
    print(f'removed {len(pIDs_before)-len(pIDs)} subjects due to fewer than 60 fixations for a key condition')
if SKIP_COMP:
    pIDs_before = pIDs
    pIDs = [p for p in pIDs if 'comprehension not different from chance' not in skip_reasons.get(p,'')]
    print(f'removed {len(pIDs_before)-len(pIDs)} subjects due to comprehension not different from chance')
if SKIP_MW:
    pIDs_before = pIDs
    pIDs = [p for p in pIDs if 'MW outside' not in skip_reasons.get(p,'')]
    print(f'removed {len(pIDs_before)-len(pIDs)} subjects due to MW outside 10-90%')
print(f'{len(pIDs)} subjects remaining after skipping')
# save skip reasons
skip_reasons = pd.Series(skip_reasons)
skip_reasons.to_csv(os.path.join(dir_out,today, 'skip_reasons.csv'))

# # %% temp: force orig 100 pIDs
# pIDs = ['EML1_028',
#  'EML1_032',
#  'EML1_034',
#  'EML1_037',
#  'EML1_038',
#  'EML1_041',
#  'EML1_042',
#  'EML1_043',
#  'EML1_045',
#  'EML1_046',
#  'EML1_047',
#  'EML1_048',
#  'EML1_049',
#  'EML1_050',
#  'EML1_052',
#  'EML1_053',
#  'EML1_055',
#  'EML1_056',
#  'EML1_058',
#  'EML1_059',
#  'EML1_060',
#  'EML1_061',
#  'EML1_062',
#  'EML1_063',
#  'EML1_064',
#  'EML1_065',
#  'EML1_066',
#  'EML1_067',
#  'EML1_068',
#  'EML1_069',
#  'EML1_070',
#  'EML1_071',
#  'EML1_072',
#  'EML1_075',
#  'EML1_076',
#  'EML1_080',
#  'EML1_081',
#  'EML1_082',
#  'EML1_083',
#  'EML1_085',
#  'EML1_089',
#  'EML1_090',
#  'EML1_091',
#  'EML1_094',
#  'EML1_095',
#  'EML1_096',
#  'EML1_097',
#  'EML1_098',
#  'EML1_100',
#  'EML1_102',
#  'EML1_103',
#  'EML1_104',
#  'EML1_106',
#  'EML1_107',
#  'EML1_108',
#  'EML1_109',
#  'EML1_111',
#  'EML1_112',
#  'EML1_114',
#  'EML1_116',
#  'EML1_117',
#  'EML1_118',
#  'EML1_119',
#  'EML1_120',
#  'EML1_121',
#  'EML1_122',
#  'EML1_124',
#  'EML1_126',
#  'EML1_128',
#  'EML1_131',
#  'EML1_132',
#  'EML1_133',
#  'EML1_134',
#  'EML1_135',
#  'EML1_136',
#  'EML1_137',
#  'EML1_139',
#  'EML1_140',
#  'EML1_141',
#  'EML1_142',
#  'EML1_143',
#  'EML1_144',
#  'EML1_145',
#  'EML1_146',
#  'EML1_147',
#  'EML1_148',
#  'EML1_149',
#  'EML1_150',
#  'EML1_151',
#  'EML1_153',
#  'EML1_154',
#  'EML1_155',
#  'EML1_157',
#  'EML1_161',
#  'EML1_162',
#  'EML1_163',
#  'EML1_165',
#  'EML1_166',
#  'EML1_169',
#  'EML1_181']
# %% reformat group results to a dict of condition keys and values is a list of evokeds one from each subject
rERP_ALL = {}
channels = ['CPz', 'FCz', 'AFF5h', 'AFF6h', 'CCP5h', 'CCP6h', 'PPO9h', 'PPO10h']
cond_combinations = {
    'Fixation' : ['reading/Fixation','sham/Fixation'],
    'FRP_MW=0': ['reading/Fixation','MW=0'],
    'FRP_MW=1': ['reading/Fixation','MW=1'], 
}
condnames = {}
for pID in pIDs:
    s = rERPs[pID]
    # refformat to dict of conditions
    for cond,c in s.items():
        condnames[cond] = cond
        # baseline correct
        c=c.apply_baseline((-.1, 0))
        # downsample to 100Hz
        c.resample(100)
        # check it contains CPz channel and skip if not
        if 'CPz' not in c.ch_names:
            print(f'{s} {cond} does not contain CPz, skipping')
            skip_reasons[pID] = f'does not contain CPz'
            pIDs.remove(pID)
            break

        if cond in rERP_ALL:
            rERP_ALL[cond].append(c)
        else:
            rERP_ALL[cond] = [c]
    # combo conditions using mne.combine_evoked
    for cc, clist in cond_combinations.items():
        # only combine if s contains all conditions
        clist = [c for c in clist if c in s]
        if not clist:
            print(f'{s} does not contain any conditions for {cc}')
            continue
        if len(clist) < len(cond_combinations[cc]):
            print(f'{s} does not contain all conditions for {cc}, will exclude missing conditions')
            continue
        res = mne.combine_evoked([s[ci] for ci in clist], weights=[1 for ci in clist])
        if cc in rERP_ALL:
            rERP_ALL[cc].append(res)
        else:
            rERP_ALL[cc] = [res]
#equalize channels 
for c in rERP_ALL:
    rERP_ALL[c]=mne.equalize_channels(rERP_ALL[c])

# combo conditions have annopying long names
condnames.update({k: ' + '.join([ vi for vi in v]) for k,v in cond_combinations.items()})


# %% t test on contrasts
contrast_conds =  [ 
    'reading/Fixation',
    ['FRP_MW=0','FRP_MW=1'],
                ['surprisal_MW=0','surprisal_MW=1'],
                ['log_word_freq_MW=0','log_word_freq_MW=1'],
                ['relative_word_position_MW=0','relative_word_position_MW=1'],
    'surprisal','log_word_freq','relative_word_position',
    ['reading/Fixation','sham/Fixation'],
    'INBOUND_SAC_AMPLITUDE',
                ]
# channels = ['FCz','CPz',['AFF5h','AFF6h'],['CCP5h','CCP6h'],['PPO9h','PPO10h']]
channels =  ['FCz','CPz']
for cc in contrast_conds:
    for ch in channels:
        if isinstance(ch, str):
            ch = [ch]
        if isinstance(cc, str) or len(cc) == 1:
            if isinstance(cc, str):
                cc = [cc]
                contrast_name = cc[0]
            x = [rERP.get_data(picks=ch) for rERP in rERP_ALL[cc[0]]]
            x = np.squeeze(np.array(x))

        elif len(cc) == 2:
            # X is list of array, shape (n_observations, p[, q][, r])
            x1 = np.array([rERP.get_data(picks=ch) for rERP in rERP_ALL[cc[0]]])
            x2 = np.array([rERP.get_data(picks=ch) for rERP in rERP_ALL[cc[1]]])
            x=np.squeeze(x2-x1)
            contrast_name = f'{cc[1]} - {cc[0]}'
        if len(x.shape)==3: # avg oevr channels
            x = np.mean(x, axis=1)
        T_obs, clusters, cluster_p_values, H0 = mne.stats.permutation_cluster_1samp_test(
                x, n_permutations=1000, seed=42, out_type='mask')  
        times = rERP_ALL[cc[0]][0].times
        fig, ax = plt.subplots()
        plotdict = {k:rERP_ALL[k] for k in cc}
        ax=plot_cluster(clusters, cluster_p_values,times, ax, tcfe=False)  
        # hold on 
        ax=mne.viz.plot_compare_evokeds(plotdict, picks=ch , axes=ax, combine='mean')
        fig.suptitle(f'Group-level {contrast_name}')
        fig.savefig(os.path.join(dir_out,today, f"Group_n=({len(pIDs)}){skip_str}_{contrast_name.replace('/','-')}_{'+'.join(ch)}.png"))
    if len(cc) == 1:
        evk = mne.grand_average(plotdict[cc[0]])
        fig=mne.viz.plot_evoked_joint(evk, picks=['eeg'], times='peaks',exclude=[])
        fig.savefig(os.path.join(dir_out,today, f"Group_n=({len(pIDs)}){skip_str}_{contrast_name.replace('/','-')}_topo.png"))




# %%
